### ISSUE TITLE
Data issue: unavailable with current valid name

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#10]
select taxon_name, current_valid_name, status, created, source, line_num, rank from taxon where current_valid_name is not null and status in ('unavailable');

+---------------------------------------------+-------------------------------------+-------------+---------------------+---------------+----------+------------+

| taxon_name                                  | current_valid_name                  | status      | created             | source        | line_num | rank       |

+---------------------------------------------+-------------------------------------+-------------+---------------------+---------------+----------+------------+

| myrmicinaetetramorium sericeiventre colluta | myrmicinaetetramorium sericeiventre | unavailable | 2015-07-15 18:42:51 | worldants.txt |    30485 | subspecies |

+---------------------------------------------+-------------------------------------+-------------+---------------------+---------------+----------+------------+

1 row in set (0.04 sec)

**Comment by jonkerz** [comment]
Merged with https://github.com/calacademy-research/antcat/issues/6#issuecomment-207843982.
