### ISSUE TITLE
Centralize docs

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#100]
This is actually multiple issues. We should have:

- [x] Antcat version
- [x] known antcat issues that can affect authors/editors
- [x] A change list (e.g.: This version introduces features foo, bar, etc).

**Comment by jonkerz** [comment]
Master has been tagged with a version number, now we just have to remember to version future commits :)

Known issues at: https://github.com/calacademy-research/antcat/wiki/Known-issues

Change list at: https://github.com/calacademy-research/antcat/wiki/Change-log-%28user-friendly%29
