### ISSUE TITLE
Notification of data issues

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#101]
We should have a mechanism to share open data issues in ancat with editors. Possibly these are issues we'd add here in "antcat issues", but maybe it would make more sense to have them accessible to anyone with editing power, who might have the ability to fix them. Possibly have it show up as a notification with the number of open data errors somewhere in the GUI.

i.e.: "list thing to fix" in the gui. ala facebook - show 15 open data issues as a red number.

  this task is to define how such information is to be shared, not to implement the feature.

**Comment by jonkerz** [comment]
Closing as "duplicate" of #130; this issue is actually older, but I wanted to put the other one at the top of the issues tracker.
