### ISSUE TITLE
Script: Synonym genera with species with incompatible statuses

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#1053]
@jonkerz @bpescador

**Issue**: The script "Synonym genera with species with incompatible statuses" is flagging junior synonym genera parenting obsolete combination names. However, both statuses are compatible—when two genera are synonymized, the species names pertaining to the junior synonym are combined with the genus name of the senior synonym (see examples below).

**Possible solution**: Add "obsolete combination" to the script's list of compatible statuses as below:

```
module DatabaseScripts
  class SynonymGeneraWithSpeciesWithIncompatibleStauses < DatabaseScript
    COMPATIBLE_STATUSES = [
      Status::SYNONYM,
      Status::HOMONYM,
      Status::OBSOLETE_COMBINATION,
      Status::UNIDENTIFIABLE,
      Status::UNAVAILABLE,
      Status::EXCLUDED_FROM_FORMICIDAE,
      Status::UNAVAILABLE_MISSPELLING,
      Status::UNAVAILABLE_UNCATEGORIZED
    ]
```

**Example 1**: _[Vollenhovia rufiventris](https://antcat.org/catalog/451231)_ was used as type-species for the genus _[Heteromyrmex](https://antcat.org/catalog/429670)_, and the name _rufiventris_ was then combined with _Heteromyrmex_ as _[Heteromyrmex rufiventris](https://antcat.org/catalog/508735)_.  Later, _Heteromyrmex_ was synonymized with _[Vollenhovia](https://antcat.org/catalog/429667)_, and the name _rufiventris_ went back to its originial combination as _Vollenhovia rufiventris_. 

**Example 2**: When the genus _[Tylolasius](https://antcat.org/catalog/429163)_ was synonymized with _[Lasius](https://antcat.org/catalog/429161)_, the name _inflatus_ (_[Tylolasius inflatus](https://antcat.org/catalog/458076)_) was combined with _Lasius_ (_[Lasius inflatus](https://antcat.org/catalog/438792)_).

**Comment by flaviaesteves** [comment]
I tried to change it by myself (see [Pull request #1054](https://github.com/calacademy-research/antcat/pull/1054/commits/ab2c15ce1272b9b5087bcdd10592dd6bb46d45e4)).

**Comment by jonkerz** [comment]
Ah! Makes sense, I will deploy the PR in the next release.

Is this the case for https://antcat.org/database_scripts/synonym_species_with_subspecies_with_incompatible_stauses as well?

**Comment by flaviaesteves** [comment]
Yes, synonym and obsolete combination are compatible in the species-subspecies scenario.
Also, thank you for changing it!
