### ISSUE TITLE
Add run notes to readme

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#109]
I've been maintaining run notes outside the GIT repo. That's bad; let's put them into the readme.

Deployment notes, architecture and testing notes, how to test, etc.

**Comment by jonkerz** [comment]
Added-ish to the wiki:
* https://github.com/calacademy-research/antcat/wiki/Deploying-on-Engine-Yard
* https://github.com/calacademy-research/antcat/wiki/For-developers

Closing issue.
