### ISSUE TITLE
Data issue: UsesCurrentValidName but has none

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#11]
mysql>  select taxon_name, current_valid_name, status, created, source, line_num, rank from taxon where current_valid_name is null and status in ('unavailable uncategorized', 'original combination', 'unavailable misspelling', 'obsolete combination', 'synonym');

+---------------------------------------------+--------------------+---------------------------+---------------------+---------------+----------+------------+

| taxon_name                                  | current_valid_name | status                    | created             | source        | line_num | rank       |

+---------------------------------------------+--------------------+---------------------------+---------------------+---------------+----------+------------+

| dorylinaeneivamyrmex fiebrigi columbicum    | NULL               | synonym                   | 2015-07-15 18:42:56 | worldants.txt |    33462 | subspecies |

| dorylinaeneivamyrmex ierense                | NULL               | synonym                   | 2015-07-15 18:42:56 | worldants.txt |    33444 | species    |

| dorylinaewoitkowskia                        | NULL               | synonym                   | 2015-07-15 18:43:02 | worldants.txt |    36333 | genus      |

| formiciinaeeoponera                         | NULL               | synonym                   | 2015-07-15 18:43:01 | worldants.txt |    35950 | genus      |

| formicinaecamponotus maculatus ruzskyi      | NULL               | synonym                   | 2015-07-15 18:43:00 | worldants.txt |    35303 | subspecies |

| formicinaecamponotus schmeltzi trotteri     | NULL               | synonym                   | 2015-07-15 18:43:00 | worldants.txt |    35265 | subspecies |

| formicinaecampostigmacros                   | NULL               | synonym                   | 2015-07-15 18:43:02 | worldants.txt |    36450 | genus      |

| formicinaechariostigmacros                  | NULL               | synonym                   | 2015-07-15 18:43:02 | worldants.txt |    36452 | genus      |

| formicinaecyrtostigmacros                   | NULL               | synonym                   | 2015-07-15 18:43:02 | worldants.txt |    36449 | genus      |

| formicinaeformica gagates piceogagates      | NULL               | synonym                   | 2015-07-15 18:42:58 | worldants.txt |    34474 | subspecies |

| formicinaeformica rufibarbis katuniensis    | NULL               | synonym                   | 2015-07-15 18:42:58 | worldants.txt |    34513 | subspecies |

| formicinaehagiostigmacros                   | NULL               | synonym                   | 2015-07-15 18:43:02 | worldants.txt |    36453 | genus      |

| formicinaelasiophanes dichrous              | NULL               | synonym                   | 2015-07-15 18:42:57 | worldants.txt |    34192 | species    |

| formicinaelasiophanes negrensis             | NULL               | synonym                   | 2015-07-15 18:42:57 | worldants.txt |    34190 | species    |

| formicinaelasiophanes rufoniger             | NULL               | synonym                   | 2015-07-15 18:42:57 | worldants.txt |    34188 | species    |

| formicinaepseudostigmacros                  | NULL               | synonym                   | 2015-07-15 18:43:02 | worldants.txt |    36451 | genus      |

| myrmicinaemonomorium bidentatum piceonigrum | NULL               | synonym                   | 2015-07-15 18:42:57 | worldants.txt |    33767 | subspecies |

| myrmicinaemonomorium rogeri                 | NULL               | obsolete combination      | 2015-07-15 18:43:12 | worldants.txt |    41497 | species    |

| myrmicinaerhopalothrix acutipilis           | NULL               | synonym                   | 2015-07-15 18:42:53 | worldants.txt |    32269 | species    |

| myrmicinaeromblonella vitiensis             | NULL               | synonym                   | 2015-07-15 18:42:53 | worldants.txt |    32191 | species    |

| myrmicinaetemnothorax pergandei flavus      | NULL               | synonym                   | 2015-07-15 18:42:52 | worldants.txt |    31780 | subspecies |

| ponerinaebelonopelta darwini madecassa      | NULL               | original combination      | 2015-07-15 18:43:07 | worldants.txt |    38628 | subspecies |

| ponerinaemegaponera abyssinica              | NULL               | synonym                   | 2015-07-15 18:42:56 | worldants.txt |    33245 | species    |

| ponerinaepachycondyla dohrni                | NULL               | synonym                   | 2015-07-15 18:42:55 | worldants.txt |    33216 | species    |

| ponerinaepachycondyla laeviuscula           | NULL               | synonym                   | 2015-07-15 18:42:55 | worldants.txt |    33196 | species    |

| ponerinaepachycondyla tarsata subopaca      | NULL               | obsolete combination      | 2015-07-15 18:43:12 | worldants.txt |    41436 | subspecies |

| ponerinaepachycondyla tarsatus subopacus    | NULL               | unavailable uncategorized | 2015-07-15 18:42:32 | worldants.txt |    20124 | subspecies |

| ponerinaepachycondyla wroughtonii crudelis  | NULL               | obsolete combination      | 2015-07-15 18:43:12 | worldants.txt |    41479 | subspecies |

+---------------------------------------------+--------------------+---------------------------+---------------------+---------------+----------+------------+

28 rows in set (0.05 sec)

**Comment by jonkerz** [comment]
Merged with https://github.com/calacademy-research/antcat/issues/6#issuecomment-207843982.
