### ISSUE TITLE
version and release notes

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#110]
We should have these.

**Comment by jonkerz** [comment]
Almost complete per #100, but we should probably add the version number (and commit hash) to the GUI on antcat.org before closing this.

**Comment by jonkerz** [comment]
Last missing piece added in f6022bd4bfa821091fcf25dfe26e64d54f5b61cf:

![version](https://user-images.githubusercontent.com/1513381/30226778-8e90e8b6-94d7-11e7-82de-4c677d4798cc.png)
