### ISSUE TITLE
Responsive layout: screenshots

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#122]
All screenshots are from working code.

![01_old_fullscreen_13_inch](https://cloud.githubusercontent.com/assets/1513381/13434297/aba5b3f4-dfd5-11e5-96dc-9e37ebae02ca.png)
![02_new_see_more_stuff](https://cloud.githubusercontent.com/assets/1513381/13434298/aba6ab38-dfd5-11e5-9039-8a3b0ab9d36d.png)
![03_new_see_more_stuff_and_browser](https://cloud.githubusercontent.com/assets/1513381/13434301/aba7fa1a-dfd5-11e5-8d9b-6fdd255b2f2e.png)
![04a_old_simulate_mobile](https://cloud.githubusercontent.com/assets/1513381/13434299/aba75a56-dfd5-11e5-918a-0573e57d9040.png)
![04b_old_real_mobile](https://cloud.githubusercontent.com/assets/1513381/13434300/aba7ea2a-dfd5-11e5-96a8-0dca874c5da3.png)
![04c_old_real_mobile_zoomed_in](https://cloud.githubusercontent.com/assets/1513381/13434302/aba8e506-dfd5-11e5-9d57-054f516b0df2.png)
![05a_new_simulate_mobile_hidden_browser](https://cloud.githubusercontent.com/assets/1513381/13434303/abba7b4a-dfd5-11e5-8818-9b00a0f062f6.png)
![05b_new_real_mobile](https://cloud.githubusercontent.com/assets/1513381/13434304/abbca7e4-dfd5-11e5-8cad-07ab44c5421c.png)
![06_new_simulate_mobile_visible_browser](https://cloud.githubusercontent.com/assets/1513381/13434305/abbcac58-dfd5-11e5-9547-56c5032770c3.png)
![07_new_some_panels_closed](https://cloud.githubusercontent.com/assets/1513381/13434306/abbcf438-dfd5-11e5-82e0-9057f121bdf2.png)
![08_new_include_invalid](https://cloud.githubusercontent.com/assets/1513381/13434307/abbdaf40-dfd5-11e5-8e6f-3640fa770aa4.png)
![09_new_valid_only](https://cloud.githubusercontent.com/assets/1513381/13434308/abbe9a04-dfd5-11e5-82b4-46995dead9c7.png)
![10_new_simulate_mobile_menu](https://cloud.githubusercontent.com/assets/1513381/13434309/abd0fbae-dfd5-11e5-97e2-c7e2a3ffdae1.png)
![11_new_references](https://cloud.githubusercontent.com/assets/1513381/13434310/abd17bc4-dfd5-11e5-9dad-5437d8826719.png)
![12_old_myrmercia_gulosa](https://cloud.githubusercontent.com/assets/1513381/13434311/abd1d358-dfd5-11e5-9020-85377590342f.png)
![13_new_myrmecia_gulosa_browser_hidden](https://cloud.githubusercontent.com/assets/1513381/13434313/abd33a68-dfd5-11e5-8774-7c398f32cdd6.png)
![14_new_myrmercia_gulosa_browser_visible](https://cloud.githubusercontent.com/assets/1513381/13434312/abd31646-dfd5-11e5-8eb9-54db46a0a509.png)

**Comment by foozleface** [comment]
Excellent. Is this pushed to a branch?

Manually ccing the rest of the team; if you’re not on this email alias, we should take steps to fix that.

-Joe

**Comment by foozleface** [comment]
Fredrik,

This is a great improvement on layout. I really appreciate you taking the
time to think through the visualization issues of the current layout and
offering a much improved version.

Unless other's see issues, I think you should work toward getting this on
the live site.

Flavia and I will be out of reach for 10 days starting tomorrow (if we get
our 4x4  repaired today).

Cheers, Brian

On Tue, Mar 1, 2016 at 7:19 PM, Joseph Russack <joe@nothingugly.com> wrote:

> Excellent. Is this pushed to a branch?
>
> Manually ccing the rest of the team; if you’re not on this email alias, we
> should take steps to fix that.
>
> -Joe
>
>
> On Mar 1, 2016, at 8:50 AM, jonkerz <notifications@github.com> wrote:
>
> All screenshots are from working code.
>
> [image: 01_old_fullscreen_13_inch]
> <https://cloud.githubusercontent.com/assets/1513381/13434297/aba5b3f4-dfd5-11e5-96dc-9e37ebae02ca.png>
> [image: 02_new_see_more_stuff]
> <https://cloud.githubusercontent.com/assets/1513381/13434298/aba6ab38-dfd5-11e5-9039-8a3b0ab9d36d.png>
> [image: 03_new_see_more_stuff_and_browser]
> <https://cloud.githubusercontent.com/assets/1513381/13434301/aba7fa1a-dfd5-11e5-8d9b-6fdd255b2f2e.png>
> [image: 04a_old_simulate_mobile]
> <https://cloud.githubusercontent.com/assets/1513381/13434299/aba75a56-dfd5-11e5-918a-0573e57d9040.png>
> [image: 04b_old_real_mobile]
> <https://cloud.githubusercontent.com/assets/1513381/13434300/aba7ea2a-dfd5-11e5-96a8-0dca874c5da3.png>
> [image: 04c_old_real_mobile_zoomed_in]
> <https://cloud.githubusercontent.com/assets/1513381/13434302/aba8e506-dfd5-11e5-9d57-054f516b0df2.png>
> [image: 05a_new_simulate_mobile_hidden_browser]
> <https://cloud.githubusercontent.com/assets/1513381/13434303/abba7b4a-dfd5-11e5-8818-9b00a0f062f6.png>
> [image: 05b_new_real_mobile]
> <https://cloud.githubusercontent.com/assets/1513381/13434304/abbca7e4-dfd5-11e5-8cad-07ab44c5421c.png>
> [image: 06_new_simulate_mobile_visible_browser]
> <https://cloud.githubusercontent.com/assets/1513381/13434305/abbcac58-dfd5-11e5-9547-56c5032770c3.png>
> [image: 07_new_some_panels_closed]
> <https://cloud.githubusercontent.com/assets/1513381/13434306/abbcf438-dfd5-11e5-82e0-9057f121bdf2.png>
> [image: 08_new_include_invalid]
> <https://cloud.githubusercontent.com/assets/1513381/13434307/abbdaf40-dfd5-11e5-8e6f-3640fa770aa4.png>
> [image: 09_new_valid_only]
> <https://cloud.githubusercontent.com/assets/1513381/13434308/abbe9a04-dfd5-11e5-82b4-46995dead9c7.png>
> [image: 10_new_simulate_mobile_menu]
> <https://cloud.githubusercontent.com/assets/1513381/13434309/abd0fbae-dfd5-11e5-97e2-c7e2a3ffdae1.png>
> [image: 11_new_references]
> <https://cloud.githubusercontent.com/assets/1513381/13434310/abd17bc4-dfd5-11e5-9dad-5437d8826719.png>
> [image: 12_old_myrmercia_gulosa]
> <https://cloud.githubusercontent.com/assets/1513381/13434311/abd1d358-dfd5-11e5-9020-85377590342f.png>
> [image: 13_new_myrmecia_gulosa_browser_hidden]
> <https://cloud.githubusercontent.com/assets/1513381/13434313/abd33a68-dfd5-11e5-8774-7c398f32cdd6.png>
> [image: 14_new_myrmercia_gulosa_browser_visible]
> <https://cloud.githubusercontent.com/assets/1513381/13434312/abd31646-dfd5-11e5-8eb9-54db46a0a509.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/122>.
>
>
>


-- 
Brian Fisher
Curator of Entomology and Patterson Scholar
55 Music Concourse Drive
California Academy of Sciences
San Francisco, CA 94118, USA
www.fisherlab.org
www.antweb.org
ResearchGate <https://www.researchgate.net/profile/Brian_Fisher7>   photos
from ongoing Fulbright in Mozambique: https://flic.kr/s/aHsku6pCu2

**Comment by jonkerz** [comment]
More screenshots.

**Merged the two search catalog functions**
Previously, the search results from the "quick" and advanced search functions were displayed on two different pages with different layouts. The quick one had too little extra info, and the advanced too much.

Old, advanced search (expanding the references makes it harder to scan the results):
![17_old_advanced_search](https://cloud.githubusercontent.com/assets/1513381/14295497/3cfc36aa-fb76-11e5-93f1-5adf415a934b.png)

Old, "quick search" (only the name is listed in the results; and the taxon description page is reused to display the results):
![18_old_quick_search](https://cloud.githubusercontent.com/assets/1513381/14295498/3cfc51ee-fb76-11e5-8e84-2bca54045373.png)

In the new layout both are merged. References are not expanded by default (but expand if clicked on, like in the catalog).

New, advanced search (easier to scan):
![19_new_advanced_search](https://cloud.githubusercontent.com/assets/1513381/14295501/3cff7748-fb76-11e5-9afd-a31f6b3415f7.png)

New, "quick search" (same layout/format as the advanced search):
![20_quick_search](https://cloud.githubusercontent.com/assets/1513381/14295499/3cfcf78e-fb76-11e5-866f-3f7d9f5ddea8.png)

**Comment by jonkerz** [comment]
Merged in d7936f54306d7a6bce7445014c66ed199246d5a9.
