### ISSUE TITLE
March deployment; issues to fix

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#123]
- [x] Edit tribe form: disable the fields for ~~protonym,~~ forms and locality (suggestion from Stan)
- [x] Cancel button needed for edit taxon: #126
- [x] Selecting subfamily in new layout #127
- [x] Trim some of the extra white space
- [x] Re-implement copy reference feature

**Comment by bpescador** [comment]
I suggest for edit tribe form:
(1) leave Protonym but delete forms locality.
(2) type must be a genus species and author not just a genus name.

**Comment by jonkerz** [comment]
@bpescador 
> (1) leave Protonym but delete forms locality.

Changed in 73126729cec5847ff60bda1a2fa5e0e9e26dfef9.

> (2) type must be a genus species and author not just a genus name.

A taxon name + an author name is already required. But allowing only genera/species names is not a straightforward change, so let's postpone this one until after this batch.

**Comment by marekborowiec** [comment]
I have to agree with Phil Ward on the following:

* The results of a catalog search must appear on the top of the page, not below the taxon browser.

* The option to copy a reference should be reinstated. I have used it a lot (and I have added many references): it's not just useful for unique combinations of authors but for all sorts of other cases, for example where there are multiple subtly different nested citations, multiple articles from the same issue of the same journal, some of the same authors etc etc.

It also appears that now the scientific name for the ant family is not Formicidae but '_Temnothorax angulinodis_'.

**Comment by jonkerz** [comment]
@marekborowiec Thanks for the feedback!

> The results of a catalog search must appear on the top of the page, not below the taxon browser.

This is largely a technical issue, but it's nothing that cannot be worked around. Yesterday I experimented with putting the TB on the left (easy to do, works pretty well) and putting it at the bottom (much harder to do). I'll get back to you regarding this.

> The option to copy a reference should be reinstated.

I may be able to re-implement this fairly quickly (the code has changed too much for the commit to be reverted).

#### Exclude
These have always been excluded from the copy feature ([link](https://github.com/jonkerz/antcat/blob/6ef34288c59802b6b087486649055e5ac67ae4ae/app/assets/javascripts/references.js.erb#L158)): **id**, **url** [PDF], **public** [PDF], **date**, **cite_code**. I suspect that the PDF-related fields were excluded for technical reasons.

Fields I think should be excluded: **title** (should be unique, I think, so excluding it means smaller chance of introducing copy-paste errors), **citation** (this is for the Other/Unknown references)

#### Include
Obvious fields to copy: **authors**, **year**
* if journal: **journal name**, **series_volume_issue**, **article_pagination**,
* if book: **publisher**, **book_pagination**
* if nested: **pages_in**, **nesting_reference_id**

#### ????
Remaining are:
* **public notes**, **editor notes** and **taxonomic notes**. Including them also makes sense.
* **possess**, include or exclude? I'm not sure what this is actually, is it something like the source from where the reference was originally imported from? According to #94, it it is supposed to be removed in the future. Here are all unique values if that helps: `"PSW", "PSW(part)", nil, "Seen(PSW)", "Seen(BB)", "PSW: pdf", "Seen", "None", "", "PSW (also pdf)", "Seen(WLB)", "PSW (pdf)", "PSW:soon", "PSW(NY ed)", "PSW(part): also pdf", "PSW(ms)", "Seen (PSW)", "PSW(trnsl)", "PSW (part)", "None. ZOOR13200020512.", "None. ZOOR13300057476. ISBN 7503817445.", "PSW: pdf (non-printable)", "None. ZOOR13700061945. ISSN 0208-7545.", "PSW: htm (available online at http://www.mos.gov.pl/pnrp/pl/num/0202/020208.htm)", "None. UCB BioSci QL1 .W28", "PSW: pdf (part)", "None. ZOOR13800000204. ISSN 0208-7545.", "None. UCB BioSci QL334.M53 Z66", "None. ZOOR13700058204. ISSN 1516-7259", "None. UCB BioSci QH600 .C494", "None. UCD Shields QL461 S55", "None.", "None. UCB BioSci QE701 .P435", "None. UCB BioSci QH7 .D6", "None. ZOOR14201006990. ISSN 0946-6193", "None. (Smithsonian QL351 .B535)", "None. ZOOR14203016157. ISBN 7533519892.", "None. CAS Mailliard QH5 .B73", "None. UCSC S&E Lib. QL1.F3", "None. UCD Shields QL461 .N35", "None. UCB BioSci QL461 .S65", "None. ZOOR14101003466.", "PSW: also pdf", "20151209"`
* **doi**, include or exclude? This one should also be unique, and I _think_ nested references don't use DOIs (but there are only 12 DOIs in the whole catalog, so it's hard to tell).

If you could let me know more specifically which fields to include, that would be great. But just getting this feature to work with the "obvious fields" would be a good start. Thing is, this change is not as straightforward as it may seem, because behinds the scenes there are for example no fields for book_pagination, article_pagination or pages_is -- there's only pagination. Simply restoring isn't possible, because the code has been rewritten (and that for good reasons).

> It also appears that now the scientific name for the ant family is not Formicidae but '_Temnothorax angulinodis_'.

Like Brian said in the email (ie the database on the test server is for testing only).

**Comment by marekborowiec** [comment]
In the copy function I would include all the 'obvious' things from your list and also taxonomic notes.

As for 'PSW', you are right, it was agreed a long time ago that this should be removed. I think you should go ahead and get rid of that field entirely if we have a blessing from Brian.

**Comment by bpescador** [comment]
I agree we should remove "PSW"

On Sun, Apr 10, 2016 at 11:43 PM, Marek <notifications@github.com> wrote:

> In the copy function I would include all the 'obvious' things from your
> list and also taxonomic notes.
>
> As for 'PSW', you are right, it was agreed a long time ago that this
> should be removed. I think you should go ahead and get rid of that field
> entirely if we have a blessing from Brian.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/123#issuecomment-208078971>
>



-- 
Photos from Mozambique: https://flic.kr/s/aHsku6pCu2

**Comment by jonkerz** [comment]
I believe everything here has been fixed (except "type must be a genus species and author not just a genus name" which we talked about in another issue thread and decided to postpone because it's not mission-critical and was not introduced in 2.0). Closing issue.
