### ISSUE TITLE
Selecting subfamily in new layout

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#127]
When selecting a subfamily in the new layout,  I think it makes sense to default to showing "All Genera:
Thus if you select Amblyoponinae:  instead of arriving at: http://ec2-52-26-62-57.us-west-2.compute.amazonaws.com/catalog/430020

you arrive here: http://ec2-52-26-62-57.us-west-2.compute.amazonaws.com/catalog/430020?display=all_genera_in_subfamily

**Comment by jonkerz** [comment]
@bpescador Good suggestion. It has been changed. To be pushed to the test branch and deployed to the test instance once I've had time to work on the other issues.
