### ISSUE TITLE
Expired security certificate

### ISSUE THREAD

**Issue by tsrsilva** [calacademy-research/antcat#1344]
I was trying to access Antcat recently and got a NET::ERR_CERT_DATE_INVALID error.

I think the site's security certification expired. I'm sending some supporting information.

![certificate expired](https://user-images.githubusercontent.com/29583489/150106358-621ebc4f-6388-4b1c-9948-d7656f6d1cda.png)

And a .txt file with the expiry date and PEM encoded chain:

[certificate antcat.txt](https://github.com/calacademy-research/antcat/files/7896192/certificate.antcat.txt)

**Comment by jonkerz** [comment]
Fixed! Thank you @tsrsilva
