### ISSUE TITLE
Advance Search: Download not working

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#135]
Example: in Advance search: http://antcat.org/catalog/search 
If you search on "Described By" for example "Ward, P. S."
on the Results page: 
1) The Download button overlaps with the Go button
2) the Download button returns:
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

**Comment by jonkerz** [comment]
@bpescador
> 2) the Download button returns:
> The page you were looking for doesn't exist.
> You may have mistyped the address or the page may have moved.

Fixed in c0a423a11a6c1ba9545d932ed799c79f1e093c6c; requires deploying

> The Download button overlaps with the Go button

Not an issue on dev, but I can see it too on the live site. Will look into it tomorrow.

**Comment by jonkerz** [comment]
Looks like both issues have been fixed, closing.
