### ISSUE TITLE
solr search crashing regularly

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#14]
Need a script to monitor and prop it back up. It also would be nice to know why it's started doing this.

**Comment by foozleface** [comment]
possible issues where that I had two errors prior: one was a too long text for the field "Type Locality" and another was I think a too long of file name for pdf for reference.  These could have caused the need for a restart.

**Comment by foozleface** [comment]
Added a newrelic hook to test search functionality, runs every ten minutes

**Comment by jonkerz** [comment]
I "merge-closed" two similar title-only issues with this one (see above). See also #44.

**Comment by jonkerz** [comment]
This seems to be fixed (but we still need to manually restart Solr after deploying).
