### ISSUE TITLE
Protonym forms not working

### ISSUE THREAD

**Issue by BradleyNReynolds** [calacademy-research/antcat#1410]
@jonkerz Not sure whether you did any work on AntCat over the weekend that could have caused the protonym forms to stop working. I keep getting error messages whenever I try to save anything.

**Comment by jonkerz** [comment]
Ahh, let me check

**Comment by jonkerz** [comment]
It works again @BradleyNReynolds, I restarted Solr

**Comment by BradleyNReynolds** [comment]
> It works again @BradleyNReynolds, I restarted Solr

Thanks!
