### ISSUE TITLE
Periodically backup Git repo

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#142]
Please close issue if we're already doing this.

There's not a too big risk of us ever messing up the whole repo, and we could probably just fix it or restore it from a random fork/checkout if that ever happens. But manually downloading major release versions from https://github.com/calacademy-research/antcat/releases seems like a sensible thing to do.

**Comment by foozleface** [comment]
I'm pretty sure that ibss-info does a nightly update from github before it does its export. I'll have to check. However, a "true" solution would do this and ensure that it's checked out (with revolving month ago, week ago, year ago trees) to a repo that's backed up on the academy repository drive.
