### ISSUE TITLE
add "add another new species"

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#145]
After adding a new species to a genus, add the option to add another species in the window that confirms taxon was created.  otherwise, you need to go back to the genus, click edit then click add a species.

**Comment by jonkerz** [comment]
@bpescador Makes sense, will try to add it before pushing 2.1. Also requested by @boud1 (AC feedback #16).

**Comment by boud1** [comment]
Thank you!

All the best,
Brendon

On Fri, Apr 29, 2016 at 12:55 PM, jonkerz <notifications@github.com> wrote:

> @bpescador <https://github.com/bpescador> Makes sense, will try to add it
> before pushing 2.1. Also requested by @boud1 <https://github.com/boud1>
> (AC feedback #16 <https://github.com/calacademy-research/antcat/issues/16>
> ).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/145#issuecomment-215862468>
>



-- 
Department of Entomology/Nematology
University of California, Davis
One Shields Ave.
Davis, CA 95616
