### ISSUE TITLE
Advanced search export format

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#147]
The Advance search is the easiest interface to access AntCat as a research tool rather than just a source of text information (like a wiki).  I suggest two changes to advance search:

~(1) For the Date, include a field for "Before" "After" or "equal"~

~For example, you could ask what species are described after 1990 in each of the Bioregions to figure out where taxonomic activity is focused.~ edit: done

(2) Have the downloadable result  be a tab delimited file with the following fields: subfamily, genus, species, subspecies,  Author, date, Country, Bioregion, Valid (yes, no), Reference.

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/73
