### ISSUE TITLE
Import and export references feature

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#148]
It's currently possible to export references to EndNote and Wikipedia's citation formats. Google Books offers BiBTeX, EndNote and RefMan. I have only used the Wikipedia format myself, and do not know what you're using. Implementing new export formats is pretty easy, and if there's interest for an import reference feature, I could take a look at that (probably easy to implement). Let me know.

**Comment by bpescador** [comment]
import as a .ris (research information system) file or .xml endnote or .enw would be a great addition.  It would greatly speed up reference entry. Download as .ris would also be very helpful.

**Comment by jonkerz** [comment]
@bpescador Can you send me a couple example files? Are multiple references usually stored in a single file? Other things I should know? :)

**Comment by bpescador** [comment]
@jonkerz  I exported three references from Mendeley (a common reference Manager).  
[reference export example.zip](https://github.com/calacademy-research/antcat/files/270110/reference.export.example.zip)

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/23
