### ISSUE TITLE
syn subspecies not in list

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#149]
@jonkerz 
Why is this taxon not in the species list for Polyrhachis.
http://antcat.org/catalog/446218

even when invalid is selected?

**Comment by bpescador** [comment]
I got it; to find a name that antcat has as subspecies, you need to know its species first. this can be problematic in larger genera.

**Comment by jonkerz** [comment]
@bpescador Closed as duplicate of #151. But I added a "Show invalid?" link next to "No valid child taxa" to make it more clear that the user must toggle to see them.
