### ISSUE TITLE
Links to pdfs don't work consistently

### ISSUE THREAD

**Issue by marekborowiec** [calacademy-research/antcat#152]
I noticed that quite a few pdf links are not reliably working, both for old entries but also including very  recently uploaded. The links in question follow to this error:
This XML file does not appear to have any style information associated with it. The document tree is shown below.

Examples include reference ids:
142924
142922
142871
129831

The funny thing is that sometimes trying to open the same pdf several times it finally works. I'm using Chrome and I'm logged in.

**Comment by jonkerz** [comment]
No fix, but here's the error message:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Request has expired</Message>
    <Expires>2016-07-20T03:45:58Z</Expires>
    <ServerTime>2016-07-20T03:51:34Z</ServerTime>
    <RequestId>182F370C82F30CDC</RequestId>
    <HostId>3w0Mo3nKUNs+zxHDV53/iCtbOy9KY8/YXjMcvAPXexZyYhx/XXLY7siwwM4q+Daaw212ppmHHys=</HostId>
</Error>
```

Probably related to some config in https://github.com/calacademy-research/antcat/blob/master/app/models/reference_document.rb

**Comment by jonkerz** [comment]
Fixed in https://github.com/calacademy-research/antcat/commit/c9ee28dca110c7f31d3bb28f76d0542b0e2688a4. Reopen if the issue reappears.
