### ISSUE TITLE
Demote genus to subgenus

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#153]
_Forelophilus_ (http://antcat.org/catalog/429306) is now a subgenus of _Camponotus_, but as far as I am concerned, there is no way to demote a genus to subgenus on AntCat. We need a tool to change ranks of supraspecific names; something like AntCat's "convert to subspecies" button.

Also, if I recall correctly subgenera were listed on AntCat. But now I cannot find them anymore. 

Any suggestion on how to solve _Forelophilus_ issue is welcome. 

Many thanks!

Flavia

**Comment by flaviaesteves** [comment]
Maybe there is no need for a "convert to subgenus" button. You could just have a subgenus as a new status.

**Comment by jonkerz** [comment]
See also #497

**Comment by jonkerz** [comment]
TODO:

- [ ] Not before #702, and and we probably need to make other changes as well

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/49.
