### ISSUE TITLE
Urgent: Issue with new combination and junior synonyms

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#156]
Hello,

If the species name being combined is a senior synonym of another species, something strange is happening, and it did not happen before.
1. After combination, a given name receives all the taxonomic history items of its junior synonym (those items are being transferred from the junior to the senior synonym);
2. The junior synonym loses all its taxonomic entry;
3. Before the combination, the junior synonym status was "synonym" of the older name; after combination, it is flagged as obsolete combination.

The correct and ideal situation would be: The junior synonym is also combined to the new genus name, but it has to keep its taxonomic history (and it cannot be added to the history of the senior name), and it will still be a junior synonym of he senior name.

For a video that contains an example of the issue, click on: https://www.dropbox.com/s/428vgie4xyx8j9l/AntCat_issues%20with%20new%20combinations.mov?dl=0

Thanks!

**Comment by jonkerz** [comment]
@flaviaesteves I'll look into it right now.

**Comment by jonkerz** [comment]
I've tracked it down do this line: https://github.com/calacademy-research/antcat/blob/69e4f57686ff2cf0aecad2823fb6d7b35e2a2cdc/app/models/taxa/save_taxon.rb#L65

It's actually an old issue predating my first commit, but it only happens whenever `previous_combination` is set to true* and if the taxon (_Camponotus cylindricus_ in this case) has junior synonyms (more precisely if there are taxa with `current_valid_taxon_id` set to that taxon's id, 432409 in this case) that has history items of their own.

\* I _think_ it's always possible to tell if this is the case by looking at the URL; in the video go to 1:58 and you'll see "new?parent_id=464151&**previous_combination_id=432409**&rank_to_create=species" in the URL.

I'll not have time to work on this but here is a pseudo-Cucumber test:
```cucumber
# Setup species + junior synoym + another species that has the same epithet (to create a name clash)
Given there is a species "Lasius clarki"
And there is a junior synonym of "Lasius clarki" named "Lasius synonymus"
And there is a species "Formica clarki"

# Setup taxonomic history items
And "Lasius clarki"  has a taxonomic history item "Senior synonym of another species"
And "Lasius synonymus" has a taxonomic history item "Junior synonym of another species"

When I go to the edit page for "Lasius clarki"
And I press "Parent"
And I change the parent to "Formica" (from "Lasius")
And I press "Yes, create new combination"
And I press "Save"

# Check that "Lasius clarki"'s history item was moved
# When I go to the edit page for <the most recent "Formica clarki" / ex "Lasius clarki"> <-- this will have a new id; you will already be on this page after pressing save, so this step is not required
Then I should see 1 taxonomic history item
Then I should see "Junior synonym of another species"

# Go to the old "Lasius clarki" page and check that there are no history items

# Check that "Lasius synonymus"'s history item was not moved
When I go to "Lasius synonymus"
Then I should see 1 taxonomic history item
```

**Comment by flaviaesteves** [comment]
Thanks @jonkerz, hope you can reproduce and fix it.

**Comment by bpescador** [comment]
@jonkerz   Phil, Flavia and I are having an AntCat meeting and the above issue came up as a high priority.  Have you any insights yet on how to move this forward?
