### ISSUE TITLE
AntCat is not updating name links in taxonomic histories, as it was before

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#157]
AntCat used to update name links in taxonomic histories. So, if a name suffered a new combination, a link for the newly combined name would substitute the link for the obsolete combination.

Example:

_Camponotus doriae_ Mayr, 1872: 137 (w.) BORNEO. Indomalaya.
Emery, 1900: 707 (s.q.). Combination in _Camponotus_: Dalla Torre, 1893: 228; in _Camponotus_ (_Colobopsis_): Forel, 1913k: 133. Junior synonym of _**Camponotus cylindricus**_: Emery, 1917a: 97.

After combination in of _Camponotus cylindricus_ in _Colobopsis_, the taxonomic history above should show: 

_Camponotus doriae_ Mayr, 1872: 137 (w.) BORNEO. Indomalaya.
Emery, 1900: 707 (s.q.). Combination in _Camponotus_: Dalla Torre, 1893: 228; in _Camponotus_ (_Colobopsis_): Forel, 1913k: 133. Junior synonym of _**Colobopsis cylindrica**_: Emery, 1917a: 97.

But the update is not happening (and it happened before).

Is it possible to make a name link automaticlly updates itself to the current valid usage of that name?

Thanks!

**Comment by jonkerz** [comment]
@flaviaesteves I'll look into it right now.

**Comment by jonkerz** [comment]
I tracked down the issue but forgot to reply here. This is actually an old issue, see #158.
