### ISSUE TITLE
S3 storage used for papers isn't backed up

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#159]
Meta issue: #924

We should download all those papers and have them in house. Also, s3 account is not currently controlled by academy.

**Comment by stanblum** [comment]
Needs a credit card other than mine, but Brian is away...

Cost is very small; less than $5/mo.

**Comment by bpescador** [comment]
I am online and can help.

Brian

On Wed, Jun 15, 2016 at 11:41 PM, Stan Blum <notifications@github.com>
wrote:

> Needs a credit card other than mine, but Brian is away...
>
> Cost is very small; less than $5/mo.
>
> On Wed, Jun 15, 2016 at 2:40 PM, Joe Russack <notifications@github.com>
> wrote:
>
> > We should download all those papers and have them in house. Also, s3
> > account is not currently controlled by academy.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/calacademy-research/antcat/issues/159>, or mute the
> > thread
> > <
> https://github.com/notifications/unsubscribe/AJWaDarbmKkOO3t__8nnSGNO-NebZD0pks5qMHFLgaJpZM4I20o9
> >
>
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/159#issuecomment-226328861>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF_GnJQjMcHuPVZtvNM3lkgHq0-Frmy0ks5qMHGZgaJpZM4I20o9>
> .
>



-- 
Brian Fisher
Curator of Entomology and Patterson Scholar
55 Music Concourse Drive
California Academy of Sciences
San Francisco, CA 94118, USA
www.fisherlab.org
www.antweb.org
ResearchGate <https://www.researchgate.net/profile/Brian_Fisher7>   photos
from ongoing Fulbright in Mozambique: https://flic.kr/s/aHsku6pCu2

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/55
