### ISSUE TITLE
Column browser issues/refactor notes

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#16]
Column browser is expensive to display, and of little use. Refactor notes:

Make it optional altogether; a clickable somethign on the bottom that makes it not display.

---

Joe, so far all is good; just one issue.  from the home page if you click on (no subfamily)  which is first subfamily.  It does not list all the genera.  

To get an idea what it should look like search on:  Eoformica 

---

I’m not sure that’s a bug as such; Eoformica is itself a Genus. It’s showing, to the left, all the available subfamilies in antcat. So, the species under Eoformica  are showing, and we see all the relevant data. It’s a little dumb to be displaying “No subfamily” as an option, but it’s not obscuring information, or showing anything incorrect.

 I’d file this under the larger issue of “The column browser isn’t the best way to display all this information”. Also, it’s very time consuming for antcat to do all the lookups to support it. A later effort would be to spend some real time looking all everything about it, and seeing how much we could get rid of. For example, maybe we don’t need to show subfamlies at all when you’re looking at the catalog entry for a genus. Or make that click-expandable.

-Joe

**Comment by jonkerz** [comment]
Closing issue as largely implemented when the taxon browser was rewritten (in AC 2.0, I believe). Performance has also been improved.

> from the home page if you click on (no subfamily) which is first subfamily. It does not list all the genera.

See http://antcat.org/catalog/429011?display=incertae_sedis_in_family
