### ISSUE TITLE
output a valid species list

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#161]
I get repeated requests for the option to output a valid species list from AntCat. Could you create an option to download a Valid species list with the following fields. Output should be csv format or other appropriate file that can be opened in excel.  This file will also allow comparison to others who generate such files such as Benoit's group.  

subfamily
genus
species
subspecies
author date
fossil (yes/no)
status = valid

**Comment by jonkerz** [comment]
Implemented in #267.

Headers + example row:
```
subfamily,genus,species,author_year,author_citation,fossil,status,antcat_id
Myrmicinae,Acanthognathus,Acanthognathus brevicornis,1944,"Smith, 1944",false,valid,430206
```

So slightly different format and no subspecies.
