### ISSUE TITLE
Cannot add new species

### ISSUE THREAD

**Issue by marekborowiec** [calacademy-research/antcat#163]
Hello,

I'm trying to add a new species, _Acromyrmex charruanus_, from reference 142745. After painstakingly adding all the details twice, I end up with the 'We're sorry but something went wrong' error message and all the info is lost; I cannot revert to the filled out form to tweak it to see what maybe causing this. Instead I need to add everything from scratch.

**Comment by foozleface** [comment]
Looks like your "type locality" is too long. It is:

URUGUAY, Florida Department, 6 km SW of Cerro Colorado, Eucalyptus globulus plantation ‘‘Plantación Cruz Roja’’, GPS coordinates: S33.9042, W055.59418, elevation 224 m above sea level, collection date: 25 February 2013, col. Bollazzi & Rabeling; collection code: CR130225-03, ex Acromyrmex heyeri nest. 

Recommendations:
We should throw a better error and/or prevent users from being able to type this much into the field. Someone else's call to determine where this information sholud go, but i'd guess 'notes'.

-Joe


:Error: Data too long for column 'verbatim_type_locality' at row 1: INSERT INTO `taxa` (`type`, `genus_id`, `status`, `name_id`, `nomen_nudum`, `ichnotaxon`, `headline_notes_taxt`, `biogeographic_region`, `verbatim_type_locality`, `type_specimen_repository`, `type_specimen_code`, `type_specimen_url`, `name_cache`, `name_html_cache`, `protonym_id`, `created_at`, `updated_at`, `subfamily_id`) VALUES ('Species', 429610, 'valid', 215838, 0, 0, '', 'Neotropic', 'URUGUAY, Florida Department, 6 km SW of Cerro Colorado, Eucalyptus globulus plantation ‘‘Plantación Cruz Roja’’, GPS coordinates: S33.9042, W055.59418, elevation 224 m above sea level, collection date: 25 February 2013, col. Bollazzi & Rabeling; collection code: CR130225-03, ex Acromyrmex heyeri nest. ', 'Museu de Zoologia, Universidade de São Paulo, São Paulo, Brazil (MZSP)', 'USNMENT00758784', '', 'Acromyrmex charruanus', '<i>Acromyrmex charruanus</i>', 200377, '2016-07-08 18:57:08', '2016-07-08 18:57:08', 429529)):

**Comment by marekborowiec** [comment]
OK, I see. What is the max length of a string I can put into the Verbatim type locality field?

**Comment by bpescador** [comment]
Joe,  I have run into this problem before and I would suggest we increase
the max string length; seems unnecessary to truncate data because of field
length.

On Fri, Jul 8, 2016 at 11:39 PM, Joe Russack <notifications@github.com>
wrote:

> Looks like your "type locality" is too long. It is:
>
> URUGUAY, Florida Department, 6 km SW of Cerro Colorado, Eucalyptus
> globulus plantation ‘‘Plantación Cruz Roja’’, GPS coordinates: S33.9042,
> W055.59418, elevation 224 m above sea level, collection date: 25 February
> 2013, col. Bollazzi & Rabeling; collection code: CR130225-03, ex Acromyrmex
> heyeri nest.
>
> Recommendations:
> We should throw a better error and/or prevent users from being able to
> type this much into the field. Someone else's call to determine where this
> information sholud go, but i'd guess 'notes'.
>
> -Joe
>
> :Error: Data too long for column 'verbatim_type_locality' at row 1: INSERT
> INTO taxa (type, genus_id, status, name_id, nomen_nudum, ichnotaxon,
> headline_notes_taxt, biogeographic_region, verbatim_type_locality,
> type_specimen_repository, type_specimen_code, type_specimen_url,
> name_cache, name_html_cache, protonym_id, created_at, updated_at,
> subfamily_id) VALUES ('Species', 429610, 'valid', 215838, 0, 0, '',
> 'Neotropic', 'URUGUAY, Florida Department, 6 km SW of Cerro Colorado,
> Eucalyptus globulus plantation ‘‘Plantación Cruz Roja’’, GPS coordinates:
> S33.9042, W055.59418, elevation 224 m above sea level, collection date: 25
> February 2013, col. Bollazzi & Rabeling; collection code: CR130225-03, ex
> Acromyrmex heyeri nest. ', 'Museu de Zoologia, Universidade de São Paulo,
> São Paulo, Brazil (MZSP)', 'USNMENT00758784', '', 'Acromyrmex charruanus', '*Acromyrmex
> charruanus*', 200377, '2016-07-08 18:57:08', '2016-07-08 18:57:08',
> 429529)):
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/163#issuecomment-231466858>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF_GnD1NWkmhJ_SCGLkw5JEbFPc0mI_iks5qTrWLgaJpZM4JIT27>
> .
>



-- 
Brian Fisher
Curator of Entomology and Patterson Scholar
55 Music Concourse Drive
California Academy of Sciences
San Francisco, CA 94118, USA
www.fisherlab.org
www.antweb.org
ResearchGate <https://www.researchgate.net/profile/Brian_Fisher7>   photos
from ongoing Fulbright in Mozambique: https://flic.kr/s/aHsku6pCu2

**Comment by jonkerz** [comment]
The max length has been changed from 255 characters to allow up to 65 k characters, closing issue.
