### ISSUE TITLE
Create new "Original orthography" field, update existing data to support it.

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#17]
Add "Originoal orthography" field to the editor

If this field is populated, show it as: 
434939:
Cerapachys davisi Smith 1942b: 64 as Cerapachys (Parasyscia) davisi, (m) U.S.A. Nearctic

formal name (the current "name) will remain in black bold.

  species with a (subspecies) notation should be copied into this "original orthography" field, and the name should have the (subspecies) removed.
# 

Cerapachys davisi Smith 1942b: 64 as Cerapachys (Parasyscia) davisi, (m) U.S.A. Nearctic

  We need to add an “original orthography” field to taxa.

  We only use the notation above if the original orthography field is populated

  We need to remove the (subspecies) notation from protonyms that used to be subspecies. These would be added as orignial orhtographies.

  Protonyms need to become first class “see” objects. We need to add these where they don’t exist. 

  Search need to return the “see” records, and they need to be able to search for “foo bar” and return “foo bar baz”. Right now you can only search for “foo bar baz” by either “foo bar baz” or “foo” “bar” or “baz”.

**Comment by foozleface** [comment]
So, from my point of view, this doesn’t require too much action; your proposals are to do with the contents, not the structure. My tasks, then, are just to update contents automatically to the degree that we all can get away with.



data tasks, as taken from your email:

1) Subgenus in parens > remove subgenus
  
  Breaking this down into two steps:
  1.1: Fix the data corruption in name where protonm_html doesn’t match name
  1.2: Create a new entry for the protonym (without subgenus), where it doesn’t exist already exist. It will point to the current valid taxa that is referenced by any entires that referenced the entry in 1.1
1.3: Do this for all protonyms, not just the parenteticals 
 (always - original combination)


2) Subspecific ranks explicit (subsp., var., st., r.) > remove rank abbreviation

  Can we safely just drop these and deal with the resulting bi, tri, and quadranomials? Or do we/can we be more clever about it? If we come up with a general rule (like your dropping, if that’s safe), then I can do this as a programmatic step (using a database query). If not, it’s a no-op for me, and I just let editors do it.

Show the words we’re pulling out, everything that ends in a period. Send list of these things.

**Comment by jonkerz** [comment]
moved to https://github.com/calacademy-research/antcat-issues/issues/23
