### ISSUE TITLE
Add species count summaries to tribal taxon pages

### ISSUE THREAD

**Issue by boud1** [calacademy-research/antcat#171]
As tribal classification is becoming much more stable with the recent work of the AToL group, I think it would be worthwhile to display species counts on tribal pages. It may be likely that several future studies will focus on particular tribes, and for this reason having a summary of species diversity would be useful. Below I have pasted the headers from the Lasiini and Formicinae taxon pages. I have put the species count summary in bold font for the subfamily entry; this summary is absent from tribal taxon pages. 

----

Lasiini Ashmead, 1905 valid
Extant: 10 valid genera (12 synonyms, 1 homonym, 17 unavailable misspelling, 11 unavailable uncategorized)

----

Formicinae Latreille, 1809 valid
Extant: 11 valid tribes (11 synonyms, 2 unavailable misspelling, 2 unavailable uncategorized), 51 valid genera (38 synonyms, 4 homonyms, 2 obsolete combinations, 136 unavailable misspelling, 85 unavailable uncategorized), <b>3,045 valid species (484 synonyms, 71 homonyms, 90 unidentifiable, 33 unavailable, 1 excluded from Formicidae, 166 obsolete combinations, 992 unavailable misspelling, 6,179 unavailable uncategorized), 816 valid subspecies (495 synonyms, 51 homonyms, 1 unidentifiable, 282 unavailable, 95 obsolete combinations, 225 unavailable misspelling, 7,629 unavailable uncategorized)</b>

[Note: text from this is extracted from an email thread with Brian, Flavia, and Joe, 3 Nov 2016. Also, I have no idea how to fix weird typological problems with this post!]

**Comment by jonkerz** [comment]
I edited your comment to fix the formatting (added some blank lines).

**Comment by jonkerz** [comment]
Added to the live site, closing issue.
