### ISSUE TITLE
Adding new history items creates 'taxon added' change events

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#180]
For example this: http://antcat.org/changes/52189

**Comment by jonkerz** [comment]
@bpescador @flaviaesteves

I could...

1) change it to say "Brian Fisher changed *Strumigenys excisa*", or

2) make the code not create any change at all.

Now with the activity log + history browser, we can track when editors add history items without this, which would mean less `Change`s to approve. One reason I favor alternative two is because adding history items is the only action that creates `Change`s in addition to saving the upper part of the taxon form. WDYT?

**Comment by bpescador** [comment]
After speaking Flavia, how about this:

If any change occurs above History, or to the synonyms, it shoudl go to
Changes

if a change only occurs in History, then it can go to activity feed.

Note in the example of "Brian Fisher changed *Strumigenys excisa*", I had
clicked the unresolved junior synonym box in the upper section, so it
probably should go to the Changes.
