### ISSUE TITLE
Load all not working

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#185]
If you click show all, or show invalid, then load all does not work.  

As an example, see: http://antcat.org/catalog/506578

**Comment by jonkerz** [comment]
@bpescador 

I cannot reproduce this issue.  I did this:

- Went to http://antcat.org/catalog/506578
- It said "Showing 500 of 1009 taxa" and showed _aana_ to _loki_.
- When I clicked on 'Load all', the button and "Showing 500 of 1009 taxa" disappeared and I could see _aana_ to _zoster_.

Does it still not work? I'm using Chrome, btw.

**Comment by bpescador** [comment]
Try this:  
http://antcat.org/catalog/429833
Showing 500 of 1009 taxa Load all?

click **show** invalid
Showing 500 of 1178 taxa

click All Taxa
Showing 500 of 1556 taxa 
A-F shown

now click Load all
A-f still shown

**Comment by jonkerz** [comment]
Thanks, I'll investigate.
