### ISSUE TITLE
Protonyms should be searchable

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#19]
By keyword and verbatim string.

searching for protonym should return. example: "Alaopone abeillei” ->  "Aenictus abeillei"

**Comment by bpescador** [comment]
@jonkerz Currently, it is difficult to search for a protonym.  Can this be added to the simple taxon search or at least the advanced search? We also need a way to link to a protonym in the taxonomic history - currently, we link to the current combination of a name - but the current combinations change and must be updated automatically - which is prone to failure - should we instead at times link to protonyms which should resolve to the current combination.

**Comment by jonkerz** [comment]
Search added in #783 (protonyms index). See #781 for including protonyms in the catalog search form.
