### ISSUE TITLE
Type information + misc notes from PSW

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#207]
Points discussed by PSW via email regarding  type status and other minor issues in AntCat: priorities for discussion:

Hi Brian, Flavia, et al.,
 
Teaching is finally over (yeah!) and I am getting back to some taxonomic work, in the course of which I have been inputting type specimen data into AntCat for some Tetraponera species. I think it is great to have this facility in AntCat but there are a few issues that have arisen.
 
“Biogeographic region”
Why is this field in the group of fields listed under Type? Why not in the Protonym boxes, after “Locality”. And why is “Locality” not called “Country”, since that is what we are usually entering here? By the way, it would be great to have a drop-down list of countries here.
 
The fields listed under Type seem to presume that there is a single primary type, but for many older names there will be a series of syntypes, sometimes from different localities and from different repositories (and comprising more than one caste). I guess in that case we can just list the multiple localities, repositories, specimen codes and url’s in the respective boxes? Is that the idea?
 
There is no place to indicate the status of the type(s): lectotype, syntype(s), holotype, or neotype. I can insert this information (awkwardly ) in the case where one of the types has been imaged, by putting it in the “Type specimen code” field, e.g., 1 syntype queen: CASENT0915850. But that will only apply to the imaged specimen (if one has been imaged). What if the syntype series consists of multiple castes? If the type(s) has not been imaged, then it is unclear how to provide this information. Maybe we need a “Type notes” field, just as there is a Protonym “Notes” field.
 
“Verbatim type locality”. This seems to be a misnomer because when one clicks on the “?” button there is a specific format called for: country, adm1, locality, coordinates, elevation, habitat, microhabitat, date, collection code, collector. So, it is NOT a precisely quoted specimen label, rather it is information culled from the specimen label (and maybe other sources). For that reason please do not automatically put quotation marks around information that is entered in this field.
 
For example, here is the type locality information that I have for the types (actually syntype queens) of Tetraponera clypeata:
Cape of Good Hope [as "Cap B. Sp."] (leg. Peringuey)
 
But after I enter this in the “Verbatim type locality” field it appears on AntCat as:
“Cape of Good Hope [as "Cap B. Sp."] (leg. Peringuey)”
 
If we are going to include more information in “Verbatim type locality” than just the verbatim type locality, then it should be up to the contributor to put quotes around  the verbatim type locality (if needed). Quotes should not be placed around all information entered in this box.
 
Incidentally “coll.” is not a good abbreviation for collector because on many older specimens (e.g., in NHMV, USNM, MCZC) “coll.” means “collection of” (e.g., Coll. G. Mayr; coll. Pergande). I suggest using “leg.”, or just put the collector name(s) in parentheses.

P.S. After playing a bit with the data entry I decided it was easiest to incorporate the information about the status of the type (syntypes, holotype, etc.) in the catch-all “Verbatim type locality” field. I did this for about ten species of Tetraponera, including T. braunsi, T. claveaui, T. clypeata, T. continua, T. gerdae, T. liengmei, T. mayri, T. penzigi, T. scotti, and T. tessmanni. Complicated cases include T. penzigi and T. tessmanni with multiple syntypes, repositories and specimen codes. Take a look at these entries and see what you think (you can see why the automatic quotes need to be removed from the “Verbatim type locality” data).

Hi Flavia,
 
Thanks for your thoughtful feedback. As you say, the naming of fields is cosmetic and they can be renamed any time—ditto for the removal of quotes from the displayed version of “Verbatim type locality”.
 
The more substantive issue concerns how to deal with multiple primary types (i.e., syntypes). I am not sure that we want to open up a whole new set of boxes for each syntype of a given species. Remember that for Tetraponera penzigi there are at least 19 syntypes! So, I was looking for a compromise that somehow captures the basic “synonymy” information that appears in taxonomic revisions. For Tetraponera penzigi this would be (excluding new synonyms that I am proposing):
 
Tetraponera penzigi (Mayr)
 
Sima Penzigi Mayr 1907b:10. Syntypes: 9 workers, 2 alate queens, 2 males, Usambara, Tanzania (Sjöstedt) (NHMV); 2 workers, Kahe, Kilimanjaro, Tanzania [as “Kilim.”] (Sjöstedt) (NHMV); 1 worker, Kahe, Kilimanjaro [as “Kilimand.”], Tanzania (Sjöstedt) (MHNG) [examined]. 1 worker syntype from NHMV imaged on AntWeb: CASENT0915851. Syntypes: 3 workers, Usambara, Tanzania (Sjöstedt) (ZMHB) [not examined]; imaged on AntWeb: FOCOL1155, FOCOL1156, FOCOL1157.
 
Sima (Tetraponera) Penzigi Mayr; Arnold 1916:180. Combination in Sima (Tetraponera).
Tetraponera penzigi (Mayr); Wheeler 1922j:800. Combination in Tetraponera.
Tetraponera penzigi (Mayr); Chomicki et al. 2015: Figure S1. Placement in molecular phylogeny.
 
By the way, when trying to enter the type information (from above) into AntCat, in the “Verbatim type locality”box, AntCat sent me an error message (“Oops. Please contact Joe Russack”, etc.) , and I lost all my unsaved edits. Despite the size of the box you cannot fill it all up with text. There is a apparently a (hidden) limit on the number of characters allowed and it is considerably less than the space provided in the box.
 
After several time-consuming attempts I was finally able to enter the following:
 
Syntypes: 9w, 2aq, 2m, Usambara (leg. Sjöstedt) (NHMV); 2w, Kahe, Kilimanjaro [as "Kilim."] (leg. Sjöstedt) (NHMV); 1w, Kahe, Kilimanjaro [as "Kilimand."] (leg. Sjöstedt) (MHNG); 3w, Usambara (leg. Sjöstedt) (ZMHB)
 
I also had a problem when I tried to enter more than one url in the “Type specimen url” box. So if multiple syntypes have been imaged one has to pick just one of them.
 
I decided that, for now, the type status information (syntype(s), holotype, etc.) and information about the numbers and castes of syntypes, is best placed in the “Verbatim type locality” field. This is especially the case for species whose types have not yet been imaged, because in that case there is no other applicable field. For example, see Tetraponera emeryi and Tetraponera zavattarii.
 
I am fine with removing “leg.” I just used it in AntCat because it has a well-known traditional meaning of “collector” among entomologists, especially Europeans. But I do not want to use “coll.” either before or after the person’s name, because of the ambiguity that it introduces (collector versus collection).

**Comment by jonkerz** [comment]
See also #183.

**Comment by bpescador** [comment]
**Published type information:**  This is the type information from the original publication.  Basically, all the type information in the publication would be cut and pasted into this field.  For modern and properly done publication, data will only need to be entered here. 

**Additional type information (from museum specimens, etc)**: This field will be field out for all older publication.  Here, type information from specimens is really important along with research as to what museums have the types.  


**Type Notes:**   This is just a notes section for when things are really complication or when discussion of specimens that are labeled type but are no longer or were never part of the type series.

**Comment by bpescador** [comment]
You can close this issue: so far, the new type fields are meeting all our needs.

**Comment by jonkerz** [comment]
Great, closing :)
