### ISSUE TITLE
Find valid species that are also synonyms

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#209]
Can you produce a databse script to find any valid species that are also has a current valid name.  I found a few examples where a species that was recently made valid but someone had forgotten to remove the "current valid name" from the previous synonym.

**Comment by bpescador** [comment]
we need to prevent the saving of a taxon that is both valid and has a current valid name.

**Comment by jonkerz** [comment]
Script added in #213, but there's still no validation. We should revisit this and a bunch of other missing validations in the future.

**Comment by jonkerz** [comment]
I'm closing this issue for now even if there's no validation, because we have a whole bunch of this kind of validation that we need to add, so let's track that in #6 (also, all current db scripts also serves as a reminder for validations we need to add to the form).
