### ISSUE TITLE
Case where the obsolete combination isn't showing up in the column browser

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#21]
I am trying to get an obselete combinatino (also the original combination) to show up on the parent page of Pachycondyla for http://antcat.org/catalog/495741

I can not get the species name insignis to show up in the list under Pachycondyla. I have tried listing it as original combination and obsolete combination.  

---

Do you mean you want "Pachycondyla insignis" to show up as “see Neoponera insignis”?

---

That part is working, I want to click on genus Pachycondyla and see that insignis is listed (in black) under the genus Pachycondyla.

**Comment by jonkerz** [comment]
@bpescador It does not show up because `display` is unchecked.

**Comment by bpescador** [comment]
I understand: I clicked display and now it shows up so can close this issue

**Comment by jonkerz** [comment]
@bpescador Should all obsolete combinations have `display` set to true? There are about 369 of them in the database.

**Comment by bpescador** [comment]
yes, can you do that automatically?

**Comment by jonkerz** [comment]
Yes, but I'd rather have an editor look through the list of taxa that would be changed before doing that.

I can create a db script for that in like 1 minute, so I'll so that and deploy it in v2.4.4 which I intend to do shortly.

**Comment by bpescador** [comment]
that works.

**Comment by jonkerz** [comment]
### Script to be executed
```ruby
taxa = Taxon.where(display: false, status: "obsolete combination")

def parameters taxon
  parent = taxon.parent
  parent_params = { rank: parent.rank,
                    name: parent.name_html_cache,
                    id:   parent.id } if parent
  { rank: taxon.rank, name: taxon.name_html_cache, parent: parent_params }
end

antcat_bot = User.find 62

taxa.find_each do |taxon|
  begin
    taxon.update! display: true
    Activity.create! trackable: taxon, action: :update,
      user: antcat_bot,# semi_automatic_edit: true, # TODO implement this!
      edit_summary: "set display to true",
      parameters: parameters(taxon)
  rescue ActiveRecord::RecordInvalid
    puts taxon.id
  end
end

jonkerz = User.find 60
Activity.create! trackable: nil, action: :execute_script,
  user: jonkerz, edit_summary: "Display all obsolete combinations; see %github21."
```

**Comment by jonkerz** [comment]
I ran the script locally but two taxa could not be updated since they have no species (which is required for subspecies). @bpescador Could you take a look?

* http://antcat.org/catalog/502723
* http://antcat.org/catalog/505081

**Comment by bpescador** [comment]
I think I deleted both of these bad records.

I am beginning to realise that we have a problem with the auto-creation of
obsolete combinations when a new combination is created.  We will need to
revisit this at one point.

Brian

On Wed, Sep 20, 2017 at 11:28 AM, Fredrik Palmkron <notifications@github.com

**Comment by jonkerz** [comment]
@bpescador The script has been run on the test instance, please see http://ec2-34-213-24-19.us-west-2.compute.amazonaws.com/activities and confirm that I should run it on live.

**Comment by bpescador** [comment]
looks good: all obsolete combinations are now set to display.  you can go
live with this.

On Wed, Sep 27, 2017 at 12:25 PM, Fredrik Palmkron <notifications@github.com

**Comment by jonkerz** [comment]
Script run on live, closing.
