### ISSUE TITLE
Duplicated synonyms

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#210]
All the Duplicated synonyms were the result of an unaware editor.  We have a choice: basically remove all such editors or fix antcat to prevent such errors.

~(1) as in the previous issue: we need to prevent the saving of a taxon that is both valid and has a current valid name~ done

We need:
(2) Can't change the parent of a species or subpecies if there are junior synonyms with the older parent.  These need to be updated first, then you can change the parent.  If you don't - you get the mess we are fixing now.

**Comment by jonkerz** [comment]
Closing stale issue. Feel free to reopen issue if it's still relevant.
