### ISSUE TITLE
advance search: number of new species per author

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#234]
I am interested in the top 10 (or top X) species describers, preferably including numbers of valid species-group names and synonymies. However, the advanced search tool is not helping calculate this information.   For example, when searching for species by Forel, I get 7,753 results. The list includes different genus combinations as well, like Acamatus bruchi vs. Neivamyrmex bruchi;  Compared to the 1,933 hits for “valid only”.  I think the valid species is correct but the other result is not - it includes the same species in different combinations (eg Acamatus bruchi vs. Neivamyrmex bruchi).  How should it be fixed?  I think it would involve looking only at protonyms instead of the names.

**Comment by jonkerz** [comment]
@bpescador 

> How should it be fixed?

We have to clean up the database, little by little. This is the most most important thing to do. #235 is a good start.

Another thing we could do is to filter the results to ignore certain taxa <-- but once we know which ones to ignore, we could probably just remove many them instead. Having more options in addition to "valid only" would be a nice addition nevertheless.

**Comment by bpescador** [comment]
the problem arises because a protonym shows up more than once (in obsolete
combinations).  The result list should only contain unique protonyms.

**Comment by jonkerz** [comment]
Added: https://antcat.org/database_scripts/number_of_protonyms_by_author
