### ISSUE TITLE
synonyms and subspecies not in same genus as the genus of the taxon record

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#237]
We need a script to locate all the species that have listed junior synonyms, senior synonyms or subspecies that are not in the same genus. 

Here is an example of a record that needs to be found and located:

http://antcat.org/catalog/507542

This is happening because when new combinations are created, they do not automatically update records in the taxonomic histories [which also needs to be fixed].

**Comment by bpescador** [comment]
One way to deal with preventing this issue in the future:  prevent creating a new combination of a parent if there are children or linking taxon that are not already changed to the new combination.

**Comment by jonkerz** [comment]
I'm not 100% I interpreted this correctly, but let's find on out the live site :smile:
