### ISSUE TITLE
Add a delete button to "see" records

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#26]
This needs to exist.

**Comment by foozleface** [comment]
Stan,

Ran out of time to fix one issue in AntCat and wonder if you could take a stab at it:

This record needs deleted:  http://antcat.org/catalog/459306

this is the correct one:  http://antcat.org/catalog/461998


Fix subspecies: they are not showing up for: http://antcat.org/catalog/443143

this issue is related to the above and may need fixed first.

**Comment by jonkerz** [comment]
"see records" can now be deleted from their edit pages, and the subspecies are now showing up. Closing issue.
