### ISSUE TITLE
show synonym for unresolved junior homonyms

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#269]
unresolved junior homonyms that are also synonyms need to show the synonym 

eg unresolved junior homonym

Crematogaster curvispinosa obscura Santschi, 1929 unresolved junior homonym

should read:  Crematogaster curvispinosa obscura Santschi, 1929 unresolved junior homonym. junior synonym of current valid taxon Crematogaster curvispinosa

**Comment by jonkerz** [comment]
Like this? I'll include it in the next release.
 
![juniorhom](https://user-images.githubusercontent.com/1513381/30515911-45bba580-9b31-11e7-9014-8371bef830ca.png)
