### ISSUE TITLE
scripts/taxa_with_same_name_and_status  and Name referencing self

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#282]
@jonkerz 

First: any idea why the script "/taxa_with_same_name_and_status"
 did not find this example of two Syllophopsis cryptobia
![screen shot 2017-09-19 at 8 53 28 pm](https://user-images.githubusercontent.com/6276764/30626128-a0a5189e-9d7c-11e7-9afa-b2eef5a3a980.png)

advance search:  syllophopsis cryptobia

Syllophopsis cryptobia see Syllophopsis cryptobia Democratic Republic Of Congo. Afrotropic. Forms: w. Santschi, 1921c
--
Syllophopsis cryptobia Democratic Republic Of Congo. "Democratic Republic of Congo." Naturhistorisches Museum, Basel, Switzerland (NHMB) Afrotropic. Forms: w. Santschi, 1921c

~~Second, can you create a script to find all cases of a name that references the same name as in:~~

~~Syllophopsis cryptobia see Syllophopsis cryptobia~~ Moved to #283

**Comment by jonkerz** [comment]
The script list only taxa with the same name and also the same status. Here one of the *Syllophopsis* is valid and the other an original combination. These are candidates for deletion, hence given their own script.

For taxa with the same name (`name_cache` to be technical`), see http://antcat.org/database_scripts/taxa_with_the_same_name_cache_value.

**Comment by bpescador** [comment]
Thank you for the link to this script: NOTE: the output/result from this
script are not for deletion: they need a careful eye to fix, and some are
correct as is.
