### ISSUE TITLE
Scan for malformed links

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#29]
I am taking this as a time to note that quite a number of references are entered in AntCat (especially at the subfamily level) in such a way that they do not expand to reveal the citation or PDF link. In most cases this is because "<et al.>" is used to shorten the author list. Whenever I see this and have the motivation to make the reference expandable I end up re-inserting the full reference. There probably is a way to fix this via coding, but I don't imagine it is or will be high priority; for now I am just calling attention to the fact that <et al.> kills the reference link.

Attached is a screen-cap with two <et al.> entries and one expandable entry.

![antcat example](https://cloud.githubusercontent.com/assets/180338/9364736/adb9e0dc-4662-11e5-8035-9da91cd08704.jpg)

**Comment by jonkerz** [comment]
Added in #200.
