### ISSUE TITLE
Don't automatically delete synonyms

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#292]
Relevant line: https://github.com/calacademy-research/antcat/blob/d4e72ccbd41fd1d6e4fb70963155db0a291a8f64/app/models/concerns/taxa/callbacks_and_validators.rb#L53

When a taxon with the status `synonym` is saved, and the status has changed to anything else, all synonym relationships where the taxon is listed as the `junior_synonym_id` are destroyed.

@bpescador @flaviaesteves Should we continue to do this? I think we're better of keeping them and let editors use the "what link here" feature to manually decide what to do.

**Comment by bpescador** [comment]
I agree they should not be destroyed automatically but how will we alert
the user to take action and to manually change them
