### ISSUE TITLE
Delete incomplete synonyms

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#311]
These: http://antcat.org/database_scripts/incomplete_synonyms

**Comment by bpescador** [comment]
when you fix the "Senior synonym: # [deleted]"  issue, can you also help figure out why this is happening?  I wonder if it results when the delete function is used on the bottom of the edit page. The synonyms are listed and if you hover over the name, you have the option to delete or reverse synonym.   Maybe one of these options is resulting in the record not being completely deleted.  I think it is worth testing.

**Comment by jonkerz** [comment]
I'm not sure why it happened, but the most recently created/edited of these synonyms was created in 2013-01-29, so it looks like this has already been fixed. The next release will also include validation that both junior and senior are set before a `Synonym` record can be created.

**Comment by jonkerz** [comment]
### Script to be run

```ruby
# "Executed a script" activity
jonkerz = User.find 60
Activity.create! trackable: nil, action: :execute_script,
  user: jonkerz, edit_summary: 'Delete incomplete synonyms; see %github311.'

# For PaperTrail
antcat_bot = User.find 62
PaperTrail.whodunnit = antcat_bot.id

# Delete
incomplete_synonyms =
  Synonym.where(<<-SQL.squish)
    senior_synonym_id IS NULL OR junior_synonym_id IS NULL
  SQL

incomplete_synonyms.each(&:destroy)
```

**Comment by jonkerz** [comment]
Executed on live: http://antcat.org/activities?id=13727#activity-13727
