### ISSUE TITLE
synonym without a current valid name

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#316]
Can you create a script to find taxa that are listed as synonyms but do not have a current valid name?  here is an example:  http://antcat.org/catalog/446384
<img width="659" alt="screen shot 2017-10-06 at 8 30 01 pm" src="https://user-images.githubusercontent.com/6276764/31304401-2fc09eda-aad5-11e7-98a9-25cff36c85f3.png">

**Comment by jonkerz** [comment]
Added here: http://antcat.org/database_scripts/synonyms_without_a_current_valid_taxon
