### ISSUE TITLE
find references without pdfs

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#324]
Meta issue: #924

There are many references that no longer have a pdf.  In edit mode, you can still see a link to the pdf but the file is gone (moved to another directory?) . Maybe these can be saved?  If not, we need to upload them again.

**Comment by jonkerz** [comment]
@bpescador Do you have an example I can investigate?

**Comment by bpescador** [comment]
@jonkerz all the links to the missing pdfs should be in the format:  http://128.146.250.117/pdfs/4498/4498.pdf 

http://128.146.250.117/pdfs/

do we have any more links with this format?

The pdfs that are missing were pdfs that were linked to HOL server - which was a poor choice because HOL changed their URLs - I have copies of all the pdfs so they could be manually uploaded

**Comment by jonkerz** [comment]
@bpescador 

`"http://128.146.250.117*"`-references were updated in #384, there are no more references containing that IP (which makes the internal method `#hosted_by_hol?` effectively useless).

Do we have other cases or can we close this issue?

**Comment by bpescador** [comment]
close issue until I can locate any that still have this problem
