### ISSUE TITLE
batch move species to a new genus

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#34]
batch move species to a new genus: maybe gender issues, additions to history

**Comment by jonkerz** [comment]
@bpescador is this the same as mass-creating combinations?

**Comment by bpescador** [comment]
@jonkerz batch move species to a new genus is the same as mass-creating combinations.  Based on our current tool, I think this will have to wait. We first want to be able to move a single species before we can batch.

**Comment by jonkerz** [comment]
TODO:

- [ ] Not before #702, and and we probably need to make other changes as well

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/49.
