### ISSUE TITLE
attribution of changes

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#359]
Attribution is correct in the Activity Feed but not correct in the history or changes list: 

Fisher changed http://antcat.org/catalog/507558/history but Brendon is showing up

<img width="1203" alt="screen shot 2017-12-13 at 1 40 15 pm" src="https://user-images.githubusercontent.com/6276764/33963838-4a77bb44-e00b-11e7-8f7e-a1cca432ecb5.png">
<img width="840" alt="screen shot 2017-12-13 at 1 40 27 pm" src="https://user-images.githubusercontent.com/6276764/33963840-4c9ad49c-e00b-11e7-9154-6bd141d6f65c.png">

<img width="881" alt="screen shot 2017-12-13 at 1 41 52 pm" src="https://user-images.githubusercontent.com/6276764/33963874-6faf47a6-e00b-11e7-891c-b3867c1b13b7.png">

**Comment by jonkerz** [comment]
I found a clue, but no solution yet.

http://antcat.org/activities?id=14515#activity-14515
http://antcat.org/catalog/429436/history
http://antcat.org/changes/55165

![ac](https://user-images.githubusercontent.com/1513381/33965603-d13a9042-e05c-11e7-8d27-255c3bd6c762.png)


![hist](https://user-images.githubusercontent.com/1513381/33965604-d1555b20-e05c-11e7-9671-0011d598d39d.png)


![change](https://user-images.githubusercontent.com/1513381/33965605-d16c3746-e05c-11e7-8ecb-5f845e5153c2.png)

**Comment by bpescador** [comment]
This is still an issue I just made a number of changes and they are still being attributed to Brendon. Maybe edits to Genus are staying with species page changes?

<img width="1258" alt="screen shot 2017-12-25 at 2 01 32 pm" src="https://user-images.githubusercontent.com/6276764/34343210-4a37134e-e97c-11e7-8823-ff1ca495fbcb.png">

**Comment by jonkerz** [comment]
@bpescador Has this been an issue lately? Say this year.

**Comment by bpescador** [comment]
@jonkerz No issues to report; though I am still not clear what types of changes trigger a listing the changes log - for example, it appears if I make a change to a history item or add a history there is no log?  not sure about that but I should check.

**Comment by jonkerz** [comment]
@bpescador Changes are only created when the taxon form is saved. So not by editing history items, but activities for the activity feed will still be created for these edits (see #180).

I'm closing this issue as it seems to be resolved.
