### ISSUE TITLE
Changes is switching editors 

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#36]
Have noticed that it happens when Brian and I are working on AntCat at the same time (on different computers, and using different logins). Basically, some of my editions will appear on Changes as made by Brian, and the same happens with some of his editions.

**Comment by foozleface** [comment]
I think this may be fixed with some of the latest fixes, specifically the ones that dealt with certain kinds of changes being non-reversable. Let me know if you still are seeing this.

**Comment by jonkerz** [comment]
Closing in favor of #164.
