### ISSUE TITLE
Link authors

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#37]
the author “Schmidt, C. A.” is the same as the author “Schmidt, C.”.

**Comment by foozleface** [comment]
![screen shot 2015-09-23 at 12 43 14 pm](https://cloud.githubusercontent.com/assets/180338/10057084/4db6b302-61f3-11e5-9c2b-7e0c99b73c89.png)

  It is possible to link authors, but this doesn't do much from the UI point of view (it creates multiple author_name entries under a single author entry). However, the process does show (per the screen shot) the affected references. These can then be cleaned up manually.

  Thought: it is possible that the author names were as published (e.g.: Bolton, B in one reference and Bolton B in another, or - more dramatically, more substantive name reference changes) it is likely unwise to have a "one true name" for a given author. 

  However, some kind of global search/replace for this (and other!) text would be very handy.

  I'll close this issue if folks think the above is true.

**Comment by jonkerz** [comment]
Closing stale issue. Feel free to reopen issue if it's still relevant.
