### ISSUE TITLE
script for citations (not nested) without pdf

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#371]
Meta issue: #924

Create a link to all citations without an available pdf.  
There are two types without a pdf:  

1) ~A citation that never had a pdf uploaded~ #783
2) A citation where AntCat at one time had a link to the pdf, but the url location of the pdf is no longer available.  

I have copies of all the pdfs, where the citation is the file name, I am hoping that we might find a way to link these to the citations with missing pdfs. If not we can upload manually.  The script would provide a list of citations that would then be opened and a file uploaded.  Tedious but doable.

**Comment by jonkerz** [comment]
closing in favor of #878
