### ISSUE TITLE
"Pass-through names": original combination, obsolete combination, unavailable misspelling

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#375]
The following refers to status:
original Combination
obsolete combination
unavailable misspelling.

All three of these statuses are "pass through" names.  It takes one name and passes through to a current combination or correct spelling.

Goal: Taxonomic history including type information, synonyms, locality should be managed in the "the current combination or correct spelling of the name".  We need to prevent users from wrongly adding taxonomic history to these pass through names. Pass through names can not have synonyms. 

Solution: For these names, only the fields that occur above the protonym authorship field should be available for editing.  All the other fields should not be visible or changeable. 

The second part is correcting what the user needs to fill in for each of these three statuses.  Currently, the only option is "Current Valid Name" which is incorrect.

For "unavailable misspelling" the box should read: "correct available spelling"

For "obsolete combination" it should read: "current combination"
For " original combination" it should read "current combination"

In all the above, the current valid name will not always be the current combination if there are synonyms involved.  We don't want the user to put the senior synonym, what should be entered is the current combination.

**Comment by jonkerz** [comment]
@bpescador Should pass through names be able to have taxonomic histories or reference sections?

**Comment by bpescador** [comment]
For pass-through names, you should not be able to add taxonomic histories - (not sure what "reference section you are referring to].  However, you can't just delete all taxonomic histories when a name becomes a pass through name. there are times when these histories need to be copied to the current combination name or correct spelling. So maybe taxonomic histories are now shown but not deleted. 
 would that work?

**Comment by jonkerz** [comment]
@bpescador Reference sections = References such as "Genus Phasmomyrmex references" on this obsolete combination: http://antcat.org/catalog/429310

Nothing will be deleted or changed automatically. I'll create two db scripts to you can find pass through names with synonyms / history items / reference sections.

**Comment by jonkerz** [comment]
Last missing piece kinda changed in 6167ce24d9d45406b1d29d73e463d3312553af3d.
