### ISSUE TITLE
Add new history items without leaving the taxon form

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#398]
@jonkerz Just found out that you need to save changes to main taxon page before the history item opens in new window.  Can you save automatically before the window opens?  or have a warning?

**Comment by bpescador** [comment]
@jonkerz I wonder if you need to open a new window?  when you edit a history item it takes place in the existing window, can that be done for new items too?

**Comment by jonkerz** [comment]
@bpescador I agree that it should be possible to add items on the same page. It requires some effort to get this working so I cannot say when it will be implemented, but I'll add a tooltip warning in the next release.

**Comment by jonkerz** [comment]
The warning was added a long time ago. I'm closing this issue since history items will change a lot in the (not near) future, so that time is better spent on other issues.
