### ISSUE TITLE
One time data issue - create migration to update review state of all references before june 2015

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#4]
Open question; it might be nice to have a superadmin feature to do this.

---
Also,  anyway to have a fresh start with this page: http://antcat.org/references?commit=new
  I would like to have all the "Start or restart reviewing" cleared for any article created before JUNE 2015.
---

migration, so far, sans the date fix:
Reference.where('review_state = “none” and ').each do | reference |
reference.start_reviewing!
end
Reference.where('review_state = "reviewing"').each do | reference |
reference.finish_reviewing!
end

**Comment by jonkerz** [comment]
Added in 6cfd51f0862c060cd9789d5dbe09e63d7cd87072.
