### ISSUE TITLE
How to raise a subgenus to genus

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#418]
In this example: http://antcat.org/catalog/429255

The subgenus should be raised to genus, but there is no way to do this; do we need a raise subgenus to genus button?

**Comment by jonkerz** [comment]
See also #497

**Comment by jonkerz** [comment]
TODO:

- [ ] Not before #702, and and we probably need to make other changes as well

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/49.
