### ISSUE TITLE
Parent: needs new taxon selector

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#419]
This taxon is an example where the Parent is actually linking to the wrong taxa, which is a homonym:
http://antcat.org/catalog/433317

Can the new taxon selector be used for Parent field?  
Because it is linking to the wrong taxa 
linking here: http://antcat.org/catalog/507602
instead of here: http://antcat.org/catalog/433726

This script is returning the taxa as an error:  http://antcat.org/database_scripts/valid_taxa_with_non_valid_parents

<img width="1102" alt="screen shot 2018-07-24 at 10 57 15 pm" src="https://user-images.githubusercontent.com/6276764/43182118-fbd999f0-8f94-11e8-969f-056efd29ae24.png">

**Comment by bpescador** [comment]
@jonkerz 

and here are two more examples where Parent is pointing to wrong species: http://antcat.org/catalog/432532
http://antcat.org/catalog/432557

**Comment by jonkerz** [comment]
This is really tricky stuff. The new taxon selector cannot be used without moving the JavaScript logic to the backend (rewriting the JS would also _work_, but we do not want that).

I may do it for fun, but there's also #450 and a lot of things I'd like to work on before this.
