### ISSUE TITLE
Update to "Adding a new taxon name guidelines"

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#42]
We need to update our guidelines to add a new taxon name, and the new version is below.

"Presume you have a new paper or found an old paper and want to upload it to AntCat and add new taxonomic actions. To do this, do the following:

1. Find out if the reference is already in AntCat by searching for the paper in the references section (antcat.org/references).

2. If the paper has already been added go to step # 3, if it has not, insert it (see Bibliography editing guidelines).

3. To make the reference the default for inserting into an AntCat entry: click “Latest additions” on the References page (the furthest left link on the green bar beneath the logo); find your reference; click on “Start reviewing”; and click on “Make default”. 
*For now, we don’t have a way to search for a reference within latest additions, and I hope it is coming soon; so, be patient… Or, you may directly add the references you want in the new species page (see step 8).

4. Now it is time to insert a new name! Navigate to the next higher taxon in which your name is classified then click the “Edit” button. Once the edit page opens, you will find a button which states “add species”/“add genus”/and so on at the right inferior corner of the page – click on it.

5. You will be redirected to a new editable page. The first field to be filled is “Name” -- just click on the “(none)” button, and fill in the name you would like to add. When it is done, click on OK. *The best strategy to avoid misspellings is to copy and paste the name from the PDF file.

6. Now go to the fields under Protonym (A.K.A. original combination). There is another field called Name, and if you click on “none” you will see the name you just copied and pasted; so, click on OK.

7. If it is a fossil name, there is a box to be checked just below the protonym name field.

8. Authorship -- Click on “(none)”, and you will see the reference you made default – thus, there is no need to search for and insert a reference; click on the default reference, and on OK. If you do need to add a new reference: search for your author in the box to add a new authorship; wait until the options to that name start to pop up just below the name you just wrote; choose one of them, and click on go (or use “search for” to look for author and year, or for a paper title – if so, after typing that, click directly on go). Now you have a list of publications from your author; choose the one you are looking for, and be sure it appears in the blue box (in that one you previously read “none”); now click on OK, and go to the next step.

9. Pages – Insert information as follows: first page of the taxon description followed by a comma, then space plus “figs.” or “fig.” depending of the number of figures that the new taxon name has in the publication (leave a space between the abbreviation and the numbers). If the figure numbers are consecutive, type the smaller number followed by a dash and the bigger number (no space between them); if they are not consecutive, type the smaller number followed by a comma, then a space, the other number, and so on. * Any figure that relates to the new taxon should be included, regardless of the figure type, including distribution map. Example: 124, figs. 1-4, 17

If you are adding a species or subspecies name, go to the next step. If you are adding a supraspecific name skip to step 12 – supraspecific taxa on AntCat have the fields “Forms” and “Locality” in blank.

10. Forms – abbreviation of the castes that were described followed by a period (w. for worker; ic. for intercaste; q. for queen; dq. for dealate queen; eq. for ergatoid queen; m. for male; em. for ergatoid male). Don`t leave a space between each caste, and be sure to not leave a space after the last caste you wrote down. Example: w.q.m.

11. Locality – Country name in which the type was described, first letter capitalized. For fossils, you should write the country’s name followed by the formation type (where the fossil was found) between parentheses. The country name will be automatically made all-capital on the taxon page. *We hope to have a pop-up list of countries and regions in the future. Example for fossils: Ukraine (Rovno Amber); for extant taxa: Australia.

12. Now go to the fields under Type, and initially, you will choose the biogeographic region in which the type was described. Finally, copy and paste the “Verbatim type locality” [A.K.A locality of primary types (holotype, lectotype, neotype or syntypes) (e.g. Brazil, São Paulo, Tapiraí, 24°01'55.5"S 47°27'56"W, 08–14 Jan 2001, col. R.R. Silva & Eberhardt, Transecto 1 Winkler 23] – This field should just contain information on the locality of original description of primary types, INCLUDING information on date, collectors, collection code, transect, and collection method, when provided.

Note: if you are adding a supraspecific name remember that the ICZN code of nomenclature requires that “The name of a type species remains unchanged even when it is a junior synonym or homonym, or a suppressed name (article 67.1.2.). In that case, please, insert the original type combination. Also, if the type is a fossil, click on the Fossil button below the type name field.

If you are adding a supraspecific name, please, skip to step 16.

If you are adding a specific or subspecific name, proceed to step 13.

13. Still under Type, add the type specimen repository. It should contain the whole name of the repository, and not just its acronym. For example, a type specimen deposited at California Academy of Sciences should have the following field entry: California Academy of Sciences, San Francisco, CA, USA (CASC). * Note that the abbreviation is between parentheses.

14. If available, add also the code of the type specimen under “Type specimen code”. Note: when a type specimen has its image on AntWeb, you can use its CASENT number (e.g., CASENT0101589).

15. Type specimen URL. If a type specimen has its image on AntWeb, you may use its stable url (not the url of its AntWeb webpage). The stable url is: www.antweb.org/specimen/the_casent_number_of_your_interest (e.g., www.antweb.org/specimen/CASENT0067685).

16. Finally, if the paper you are working on also provides important information on a genus, or species, you should also add in an appropriate field on AntCat. 

For example, if the author(s) designated a lectotype or neotype for a given name, go to that name, and under the editing mode, add that information to its taxonomic history. Something like: Rakotonirina & Fisher, 2014: 42 (lectotype designation). Please, see more information on how to add a taxonomic history entry on Adding a taxonomic history entry guidelines. 

If the author(s) provided an identification key of any sort for a given genus (or supraspecific taxon), add that information to the genus references – editing mode of the genus AntCat entry. It would be something like: Rakotonirina & Fisher, 2014: (Malagasy species revision, identification key). Please, see more information on how to add a genus reference on Adding supra-specific taxa important references guidelines].

17. Click on Save, and it is done! Thank you for contributing to AntCat!! "

**Comment by jonkerz** [comment]
Merged with "Adding a new species" and renamed to "Adding a new taxon": https://github.com/calacademy-research/antcat/wiki/Adding-a-new-taxon
