### ISSUE TITLE
+reference: add pages from ref to pulldown

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#421]
@jonkerz 
Adding references to Taxonomic Histories from Bolton's updated Cat is a slow process because there is not a one to one match between AntCat and Bolton citations.  

the normal process is to paste into a new Taxon history and then link references. Here is an example:
**Status as species**: Smith, F. 1858b: 79; Roger, 1859: 245; Mayr, 1861: 54 (in key); Roger, 1861a: 23; Mayr, 1862: 712; Roger, 1863b: 21; Mayr, 1863: 394; André, 1874: 188 (in key); Emery & Forel, 1879: 455; André, 1882b: 231 (in key); Emery, 1884a: 378 (in key); Saunders, E. 1890: 203; Dalla Torre, 1893: 47; Emery, 1909c: 375; Forel, 1909c: 103; Emery, 1911d: 108; Crawley, 1920a: 163; Emery, 1924c: 164; Santschi, 1931a: 2; Santschi, 1936c: 198; Ceballos, 1956: 295; Brown, 1964d: 214; Collingwood & Yarrow, 1969: 55; Brown, 1978c: 556, 598; Collingwood, 1978: 75 (in key); Bolton, 1995b: 64; Cagniant, 2006a: 195; Tinaut, et al. 2011: 161; Borowiec, L. 2014: 8.

We need to find a way to speed up the tedious linking of references.  Here are some options that might work:
(1) if no letter present [eg Mayr, 1862] then link automatically from Antcat if reference present in AntCat.
(2) if letter present, then manually add link [eg Smith, F. 1858b: 79]

I see two things that could help speed up manual links. 
(a) can you add the pages to the references in the pull-down?  in the above example, the correct reference will be the one that includes the page range 79.

(b) another option is that for all references with letters, we could add to an existing field, maybe in the "Editor note" field the Bolton reference such as "Bolton:1858b" and have that present in the pull-down?

If you want to see the scope of the challenge, I am attaching a few genera of Barry's Updated Cat. Our challenge is how we are to add all these new references to each taxon
. How much can be down automatically and how much needs to be done by hand. 

[part5.pdf](https://github.com/calacademy-research/antcat/files/2233128/part5.pdf)

**Comment by jonkerz** [comment]
a) and b) are quite easy.

TODO:
- [ ] Include pagination (and `pages_in` for nested references) in the autocomplete suggestions
- [ ] Include any Bolton key if there is any (create this as a new reference field)
