### ISSUE TITLE
Automatically parse plain text Bolton references to reference tags

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#423]
See #421.

So `Roger, 1859` becomes `{ref 128086}`.

**Comment by jonkerz** [comment]
Added in 8c4cc32450db73cb82813594c643f820672654ec. Can be made more user-friendly and integrated with the taxt editor in the future.

**Comment by bpescador** [comment]
@jonkerz I am looking forward to using the "[Bolton keys to ref tags](http://antcat.org/panel/bolton_keys_to_ref_tags)" more often.  Could this tool be added to the new history item tool?  I often want to use it when I am creating a new history item and I want to copy text from Bolton's word file.

**Comment by jonkerz** [comment]
Let's do it :)

**Comment by jonkerz** [comment]
@bpescador Please check now, for example this one: http://antcat.org/reference_sections/2918/edit

**Comment by bpescador** [comment]
Fredrik,

The example you provides a good test case for finding citation formats that
don't convert.  You can see here which ones did not convert.  So how do we
make the tool convert the ones that did not.

Can you think of a way to make it convert those with "&" such as:
Brown & Nutting, 1950
Raignier & Boven, 1955: 86
Wheeler, G.C. & Wheeler, J. 1972:
Wheeler, G.C. & Wheeler, J. 1976
Gotwald & Burdette, 1981

It should be noted that the example you gave uses Bolton 2003 publication
on subfamilies as references and not his normal ant catalog references used
for species and genera. But the issue with & is the same.

Brian

**Comment by jonkerz** [comment]
> Can you think of a way to make it convert those with "&" such as:

These were not converted because they have to Bolton key on AC. Bolton keys must be set in the reference form.

I added a fix so that they show up in the reference search results when you select the hardcoded reference and press "+Reference".

> It should be noted that the example you gave uses Bolton 2003 publication on subfamilies as references and not his normal ant catalog references used for species and genera.

Does this mean that Bolton keys are not "universal" or permanent?

I believe most AC keys and Bolton keys are the same, with the exception of nested references, so we could change the conversion script to look for any key that is the same if there is no Bolton match on AC. I think there will not be that many false positives if we ignore nested references and keys with letters after the year.

**Comment by bpescador** [comment]
Fredrik,

I am working with the Bolton text key converter.  I am able to make all
citations convert but for those that include initials.  Based on my work
today I have the following examples that need to be hard coded.

Smith, D.R. 1979: 1335

 Smith, M.R. 1928b: 243

 Smith, M.R. 1930a: 2

 Smith, M.R. 1951a: 783

 Smith, M.R. 1958c: 110

 Smith, M.R. 1967: 346

 Wesson, L.G. & Wesson, R.G. 1940: 90

 Wheeler, G.C. & Wheeler, J. 1986g: 17

Wheeler, W.M. 1900c: 56

 Wheeler, W.M. 1904e: 299

 Wheeler, W.M. 1905f: 374

 Wheeler, W.M. 1906b: 1

 Wheeler, W.M. 1908e: 399

 Wheeler, W.M. 1910g: 561

 Wheeler, W.M. 1913c: 112

 Wheeler, W.M. 1917i: 460

 Wheeler, W.M. 1932a: 2

Here is some text you can test with:

Status as species: Roger, 1863b: 20; Mayr, 1863: 457; Mayr, 1886d: 439;
Cresson, 1887: 259; Dalla Torre, 1893: 14; Emery, 1895c: 261; Wheeler, W.M.
1900c: 56; Wheeler, W.M. 1904e: 299; Wheeler, W.M. 1905f: 374; Wheeler,
W.M. 1906b: 1; Wheeler, W.M. 1908e: 399; Wheeler, W.M. 1910g: 561; Emery,
1911d: 24; Wheeler, W.M. 1913c: 112; Wheeler, W.M. 1917i: 460; Smith, M.R.
1928b: 243; Smith, M.R. 1930a: 2; Wheeler, W.M. 1932a: 2; Dennis, 1938:
275; Wesson, L.G. & Wesson, R.G. 1940: 90; Creighton, 1940b: 3
(redescription); Brown, 1949c: 84; Creighton, 1950a: 33; Smith, M.R. 1951a:
783; Cole, 1953c: 84; Smith, M.R. 1958c: 110; Whelden, 1958: 1; Brown,
1960a: 169, 183, 192 (in key); Carter, 1962a: 6 (in list); Francoeur &
Béique, 1966: 141; Smith, M.R. 1967: 346; Hunt & Snelling, 1975: 20;
Francoeur, 1977b: 206; Francoeur, 1979: 34 (redescription); Smith, D.R.
1979: 1335; Traniello, 1982: 65; Wheeler, G.C. & Wheeler, J. 1986g: 17;
DuBois & LaBerge, 1988: 135; Ward, 1988: 105; Deyrup, et al. 1989: 92;
Lattke, 1991c: 6 (in key); Bolton, 1995b: 62; Lacau & Delabie, 2002: 40 (in
key); Mackay & Mackay, 2002: 31; Deyrup, 2003: 44; Coovert, 2005: 23;
MacGown & Forster, 2005: 67; Ward, 2005: 25; Ellison, et al. 2012: 89;
Deyrup, 2017: 13.


2). regards to your comment:
I believe most AC keys and Bolton keys are the same, with the exception of
nested references, so we could change the conversion script to look for any
key that is the same if there is no Bolton match on AC. I think there will
not be that many false positives if we ignore nested references and keys
with letters after the year.

If there is no letter in AC and no letter in Bolton key, then it is safe to
assume they are the same; however, if ac has a letter then you need a key.

So why do we need letters in AC?  is that necessary?
