### ISSUE TITLE
author search returns invalid hits

### ISSUE THREAD

**Issue by PeterHawkes** [calacademy-research/antcat#424]
When searching for publications including a particular author, the search engine returns what it considers to be similar authors, even if a strict search is specified by putting quotes around the name.

Examples "Hawkes" returns hits including Hawks, "Dowling" returns hits including Dowler

While breaking Boolean logic appears to be the norm for search engines these days, this takes it to a new level by preventing an exact term from being specified at all...

**Comment by bpescador** [comment]
@PeterHawkes 
For author exact search, if you use the autocomplete for the author, you are doing an exact  author search; see the example for Hawkes

<img width="1562" alt="screen shot 2018-07-27 at 5 55 16 am" src="https://user-images.githubusercontent.com/6276764/43321898-115d82d6-9162-11e8-98c7-d05bd98a5f20.png">

**Comment by PeterHawkes** [comment]
Hmm...somehow it doesn't work like that from here; with "search by author(s)" selected, the autocomplete does not work and if I fill in the full name manually and click "go" it returns "no results".  

Filling in a partial name with "search all fields" selected gives me a drop-down of hits to select from, but to get a list similar to what you have above (but lacking the "Taxonomic notes:" bits) I have to manually type in the full name (Hawkes, P.G.;) and select "go":

![antcat](https://user-images.githubusercontent.com/41116550/43323780-da3651d8-91b2-11e8-8fa5-721a0f52739f.JPG)

I've tried two browsers on this machine; will try some other PCs to check whether it is a machine or location (?internet connection) problem...

**Comment by bpescador** [comment]
Peter,

try "search by author(s)" but just start with "Hawkes" then choose the
author.  of if you paste, Hawkes, P.G. backspace until autocomplete is
working.

**Comment by PeterHawkes** [comment]
If I just type Hawkes and wait, nothing happens (not even when I leave it for half an hour or more); ditto for pasting in Hawkes, P.G. and backspacing - no auto complete activity....  I'll try another PC next...

**Comment by jonkerz** [comment]
@PeterHawkes You could also try the `author:` keyword, like this: http://antcat.org/references/search?utf8=%E2%9C%93&search_type=all&q=author%3A%27Hawkes%2C+P.+G.%27&author_q=

Autocompletion should work if you use "Search all fields" and type `author:haw` and then click on the first reference, or if you do what Brian said.

It would make more sense if `"Hawkes"` in quotes only returned exact matches, but I do not know how to config that. I'll investigate if it's an easy thing to do, but I'm afraid it's not going to be a quick fix.

**Comment by PeterHawkes** [comment]
Thanks - have tried another machine as well and on both the search all fields options specifying "author:haw" or "author:"Hawkes, P.G." seems to work, but I can't get anything to work in the search by authors option - and can't replicate the results list as Brian showed it with the taxon comments!

However, there is at least a way of getting only the results I want - though it would be nice if the "hawkes" in quotes in the search by author worked (I get no hits at all this way) - so for now I'll work through the search all fields option....

**Comment by bpescador** [comment]
Peter,
can you share screen shot of your  search by author results

**Comment by PeterHawkes** [comment]
I've tried various ways of entering the author in "search by author" (with & without quotes, just the first few letters or the full name and with/without the initials and all essentially return:

![antcat2](https://user-images.githubusercontent.com/41116550/43346008-e6163bac-91ef-11e8-80dd-8f315b40dd31.JPG)

**Comment by bpescador** [comment]
for authors, you need to use the pull down, if not try the name in AntCat
format, with space between initials followed by ;  eg . "Hawkes, P. G.; "
without quotes

**Comment by PeterHawkes** [comment]
autocomplete or pull down does not appear for me if I type in partial names, but I now see that when I put the full name in I was omitting the space e.g. between P. and G. - now if I try Hawkes, P. G. I do get the correct list (still without the "taxonomic notes" that were in your list though, but this is not important).  So as long as I get the exact author name correct, I should be OK

Thanks!

**Comment by bpescador** [comment]
if you login to AntCat I think you will get the taxonomic notes.

Are you using Chrome?  can you try an updated version of chrome and see if
it works.

**Comment by PeterHawkes** [comment]
I'll try logging into AntCat first...have mainly been using FireFox, but tried Chrome also (old version on one PC, up-to-date version on another).

Will try some more tomorrow...

**Comment by jonkerz** [comment]
Closing as it seems to work as expected.

**Comment by PeterHawkes** [comment]
Not sure this should be closed yet as I am still unable to get autocomplete to work...if I select "search by author(s)" and type a partial name, nothing happens. No matter how long I wait, nor how much of the name I fill in.  Not sure if this could be due to South Africa not having a fast enough connection to the rest of the world, but my connection runs at about 20mpbs, so should be more than adequate.

**Comment by PeterHawkes** [comment]
Yes - if I click on the link, I get the correct list of results...and I get the same if I type in the full and exact Hawkes, P. G. - but anything less than this (even removing just the second period - after G) gives me "no results found" and the autocomplete does not offer any options.

**Comment by jonkerz** [comment]
Peter, what browser and version are you using?

**Comment by PeterHawkes** [comment]
Firefox 52.9.0 (32-bit) on one machine, Chrome 69.0.3497.100 (64 bit) on the other; in both cases I can't get the autofill in author search to work

**Comment by PeterHawkes** [comment]
The Firefox is old (most recent that will run on a very old PC with WinXP!), the Chrome is the latest version, running on a Win7 64-bit PC.

**Comment by PeterHawkes** [comment]
Having said that, Chrome on Win7 must have heard what I was typing and immediately updated itself to 70.0.3538.67 but the autofill still doesn't work.

**Comment by bpescador** [comment]
@jonkerz 
Searching on authors is still an issue.  There are two types of issues:

1) references not listed alphabetically:  here is a message:

While on the subject, I looked through the AntCat bibliography of Dlussky's papers. They seem awfully confused as they do not appear to be in chronological or alphabetical order. Is this policy, or has something gone awry? It makes it quite difficult to scan through looking for a particular reference.

I first searched the refs using Dlussky, G. M. This produced quite chaotic results in terms of alphabetical and chronological sequence. I have just tried your suggestion, author: Dlussky, and that is better, but there are still lots of refs that are not alphabetical, or chronological, probably because the machine looks for anything with Dlussky in it. It is disconcerting to find first authors such as Sonobe, Kaulfuss, Atanassov, Wappler, etc. under Dlussky, just because his name appears somewhere in the list of contributors.

2) the second is that some authors don't show up when searching, eg: 

eg if you search for: "McArthur, 2010"

you will not find: http://antcat.org/references/132766

To find that publication you need to search: "Mcarthur, 2010"

if you search Arnol'di, 1968
you won't find: http://antcat.org/references/122361

you need to search "Arnol'd, 1968"

why does removing the 'i" from the end of Arnol'di make the search work?
