### ISSUE TITLE
Name cache sync broken?

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#44]
Deleted bolton, b. then tried to save, and it went splat.
url:
http://www.antcat.org/references?commit=Go&is_author_search=false&page=5&q=bolton&review=false&search_selector=Search+for&utf8=%E2%9C%93&whats_new=false

  bolton was a double entriy in names, and we can't delete just one.
deleted the one, and now when we go to save a paper with the above URL, it craters like the below.

Note that "merge references" will show usages! edit_. merge

07 #6010]  INFO -- :   Parameters: {"term"=>"Bolton,"}
I, [2015-09-04T21:30:24.332010 #6010]  INFO -- : Completed 200 OK in 16ms (Views: 0.1ms | ActiveRecord: 6.4ms | Solr: 0.0ms)
I, [2015-09-04T21:30:28.749417 #6010]  INFO -- : Started PUT "/references/122823" for 12.189.20.125 at 2015-09-04 21:30:28 +0000
I, [2015-09-04T21:30:28.751171 #6010]  INFO -- : Processing by ReferencesController#update as HTML
I, [2015-09-04T21:30:28.751300 #6010]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Lw+FVWAm4C/IBjyGBmudAgv/sauJE8Lf9vuxdN1T+0ErpUkmtBCTjcfM86VEzY/5J/kLa5ehc+lRc/clPYwUTw==", "selected_tab"=>"Article", "possible_duplicate"=>"", "reference"=>{"author_names_string"=>"Bolton, B.; ", "citation_year"=>"1972", "title"=>"Two new species of the ant genus _Epitritus_ from Ghana, with a key to the world species (Hym., Formicidae)", "journal_name"=>"Entomologist's Monthly Magazine", "series_volume_issue"=>"107", "publisher_string"=>"", "pages_in"=>"", "nesting_reference_id"=>"", "citation"=>"", "document_attributes"=>{"url"=>"http://antcat.org/documents/236/6423.pdf", "public"=>"0", "id"=>"236"}, "public_notes"=>"", "editor_notes"=>"Date from Bolton.", "taxonomic_notes"=>"", "cite_code"=>"2672", "possess"=>"PSW", "date"=>"19720609"}, "article_pagination"=>"205-208", "book_pagination"=>"205-208", "id"=>"122823"}
I, [2015-09-04T21:30:28.805708 #6010]  INFO -- : Completed 500 Internal Server Error in 54ms (ActiveRecord: 26.5ms)
F, [2015-09-04T21:30:28.807276 #6010] FATAL -- : 
RSolr::Error::Http (RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>0},'error'=>{'msg'=>'java.io.FileNotFoundException: /data/antcat/releases/20150828001735/solr/./default/data/tlog/tlog.0000000000000000026 (No such file or directory)','trace'=>'org.apache.solr.common.SolrException: java.io.FileNotFoundException: /data/antcat/releases/20150828001735/solr/./default/data/tlog/tlog.0000000000000000026 (No such file or directory)
    at org.apache.solr.update.TransactionLog.<init>(TransactionLog.java:182)
    at org.apache.solr.update.TransactionLog.<init>(TransactionLog.java:140)
    at org.apache.solr.update.UpdateLog.ensureLog(UpdateLog.java:796)
    at org.apache.solr.update.UpdateLog.add(UpdateLog.java:358)
    at org.apache.solr.update.UpdateLog.add(UpdateLog.java:344)
    at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:225)
    at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
    at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:451)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:587)

URI: http://localhost:8983/solr/default/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">ArticleReference 122823</field><field name=\"type\">ArticleReference</field><field name=\"type\">UnmissingReference</field><field name=\"type\">Reference</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">ArticleReference</field><field name=\"type_s\">ArticleReference</field><field name=\"year_i\">1972</field><field name=\"citation_year_s\">1972</field><field name=\"author_names_string_s\">Bolton, B.</field><field name=\"author_names_string_text\">Bolton, B.</field><field name=\"citation_year_text\">1972</field><field name=\"title_text\">Two new species of the ant genus _Epitritus_ from Ghana, with a key to the world species (Hym., Formicidae)</field><field name=\"journal_name_text\">Entomologist's Monthly Magazine</field><field name=\"citation_text\"/><field name=\"cite_code_text\">2672</field><field name=\"editor_notes_text\">Date from Bolton.</field><field name=\"public_notes_text\"/><field name=\"taxonomic_notes_text\"/></doc></add>"

Backtrace: /data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in`execute'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:16:in`block in send_and_receive_with_as_instrumentation'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:15:in`send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:82:in`update'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:102:in `add'):
  app/models/reference.rb:117:in`refresh_author_names_caches'
  app/controllers/references_controller.rb:73:in `block in save'
  app/controllers/references_controller.rb:62:in`save'
  app/controllers/references_controller.rb:57:in `update'
  config/initializers/quiet_assets.rb:8:in`call_with_quiet_assets'

I, [2015-09-04T21:30:39.552565 #6010]  INFO -- : Started GET "/references?utf8=%E2%9C%93&search_selector=Search+for&q=foo&commit=Go" for 184.73.237.85 at 2015-09-04 21:30:39 +0000
I, [2015-09-04T21:30:39.554140 #6010]  INFO -- : Processing by ReferencesController#index as _/_
I, [2015-09-04T21:30:39.554190 #6010]  INFO -- :   Parameters: {"utf8"=>"✓", "search_selector"=>"Search for", "q"=>"foo", "commit"=>"Go"}
I, [2015-09-04T21:30:39.560352 #6010]  INFO -- :   Rendered shared/_qtip.html.haml (0.1ms)
I, [2015-09-04T21:30:39.560430 #6010]  INFO -- :   Rendered references/_search.html.haml (0.7ms)
I, [2015-09-04T21:30:39.560612 #6010]  INFO -- :   Rendered references/index.haml within layouts/application (2.0ms)
I, [2015-09-04T21:30:39.563165 #6010]  INFO -- :   Rendered shared/_login.html.haml (0.9ms)
I, [2015-09-04T21:30:39.563736 #6010]  INFO -- :   Rendered shared/_site_header.haml (1.8ms)
I, [2015-09-04T21:30:39.564848 #6010]  INFO -- :   Rendered shared/_site_footer.html.haml (0.9ms)
I, [2015-09-04T21:30:39.569696 #6010]  INFO -- : Completed 500 Internal Server Error in 15ms (Views: 6.8ms | ActiveRecord: 0.0ms | Solr: 6.4ms)
F, [2015-09-04T21:30:39.570701 #6010] FATAL -- : 
RSolr::Error::Http (RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>2},'error'=>{'msg'=>'_11_Lucene41_0.tip','trace'=>'java.io.FileNotFoundException: _11_Lucene41_0.tip
    at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:265)
    at org.apache.lucene.store.NRTCachingDirectory.fileLength(NRTCachingDirectory.java:177)
    at org.apache.lucene.index.SegmentInfoPerCommit.sizeInBytes(SegmentInfoPerCommit.java:88)
    at org.apache.lucene.index.TieredMergePolicy.size(TieredMergePolicy.java:674)
    at org.apache.lucene.index.TieredMergePolicy.useCompoundFile(TieredMergePolicy.java:653)
    at org.apache.lucene.index.IndexWriter.useCompoundFile(IndexWriter.java:2211)
    at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:563)
    at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:533)
    at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:422)
    at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:559)

URI: http://localhost:8983/solr/default/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><commit softCommit=\"false\"/>"

Backtrace: /data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in`execute'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:16:in`block in send_and_receive_with_as_instrumentation'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:15:in`send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:82:in`update'
/data/antcat/shared/bundled_gems/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:111:in `commit'):
  config/initializers/quiet_assets.rb:8:in`call_with_quiet_assets'

I, [2015-09-04T21:31:14.204727 #6010]  INFO -- : Started GET "/references?utf8=%E2%9C%93&search_selector=Search+for&q=foo&commit=Go" for 50.31.164.139 at 2015-09-04 21:31:14 +0000
I, [2015-09-04T21:31:14.206785 #6010]  INFO -- : Processing by ReferencesController#index as _/_
I, [2015-09-04T21:31:14.206843 #6010]  INFO -- :   Parameters: {"utf8"=>"✓", "search_selector"=>"Search for", "q"=>"foo", "commit"=>"Go"}
I, [2015-09-04T21:31:14.212977 #6010]  INFO -- :   Rendered shared/_qtip.html.haml (0.1ms)
I, [2015-09-04T21:31:14.213055 #6010]  INFO -- :   Rendered references/_search.html.haml (0.8ms)
I, [2015-09-04T21:31:14.213230 #6010]  INFO -- :   Rendered references/index.haml within layouts/application (2.1ms)
I, [2015-09-04T21:31:14.215829 #6010]  INFO -- :   Rendered shared/_login.html.haml (0.9ms)
I, [2015-09-04T21:31:14.216419 #6010]  INFO -- :   Rendered shared/_site_header.haml (1.9ms)
I, [2015-09-04T21:31:14.217517 #6010]  INFO -- :   Rendered shared/_site_footer.html.haml (0.9ms)
I, [2015-09-04T21:31:14.217851 #6010]  INFO -- : Completed 200 OK in 11ms (Views: 6.9ms | ActiveRecord: 0.0ms | Solr: 6.9ms)
deploy@ip-172-31-12-161 ~ $

**Comment by jonkerz** [comment]
Classic Solr :smile:
