### ISSUE TITLE
test scripts for testing converting plain text content from Bolton into AntCat markup

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#443]
Use existing references in taxonomic histories and patronyms to test the tool that converts plain text content from Bolton into AntCat markup (referred to below as the conversion tool)

To validate conversion tool: could you write a script to evaluate all existing markups that already exists to see if the conversion tool would return the same linked reference?  If not, could you have the script indicate with references would wrongly be converted with your new converting tool? 

Could you write a script to list all references without a Bolton Key

**Comment by jonkerz** [comment]
>  Could you write a script to list all references without a Bolton Key

https://antcat.org/database_scripts/references_without_bolton_keys

Added in 2e38f235f37039bdc9ccbb4c7c3d72112cee2419
