### ISSUE TITLE
We have to change "How to cite AntCat"

### ISSUE THREAD

**Issue by flaviaesteves** [calacademy-research/antcat#45]
1. The year is outdated.
2. Will it be forever Bolton. Year. AntCat?

**Comment by jonkerz** [comment]
Year has been updated on the test server.

**Comment by jonkerz** [comment]
See also: https://groups.google.com/forum/#!topic/antcat/6s5RjQmqI8Y

**Comment by jonkerz** [comment]
I agree with the change, but closing as stale until it has been decided how it should be changed.
