### ISSUE TITLE
Revisit how incertae sedis taxa are stored in the database

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#453]
In some places we make use of the fact that `Genus` records without a `subfamily_id` are _incertae sedis_ by implication, but we also have the db column `taxa.incertae_sedis_in` (a string which will be `family` or `subfamily`, etc).

**Comment by bpescador** [comment]
if you write a script for those missing the taxa.incertae_sedis_in data I can fill them in or you can do it automatically.  Also, we need a way to search on all incertae_sedis taxa in advanced search.

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/23.
