### ISSUE TITLE
Author field in new references

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#479]
@jonkerz The author field is listing not unique names but it appears to be listing unique name and date combinations. see image.
<img width="561" alt="screen shot 2018-10-25 at 5 30 15 am" src="https://user-images.githubusercontent.com/6276764/47500294-46e41400-d817-11e8-9cf9-2b07d5a326b7.png">

**Comment by jonkerz** [comment]
@bpescador I have a fix for this in #474. If you have had time to look at the new parent selector we can deploy it today.

**Comment by bpescador** [comment]
@jonkerz I think it is ready to be released but to help clarify the differences between the two options for changing parent, add help text to the Create Combination tool:  eg http://ec2-35-165-205-57.us-west-2.compute.amazonaws.com/taxa/460095/create_combination/new

Something like:  
Create Combination will create a new taxon record for the new combination and will change the status of the previous usage to "obsolete combination."

Also, in the help text for the force parent, change the second sentence to:
Force-changing parent will modify the record in place without creating a new record. 

Help
Please only use this functionality to correct obvious mistakes such as species that are listed in the wrong genus and never should have been there (homonyms, for example). Force-changing parents modifies the records in place without creating new recods. Use the "Create combination" button to create combinations.

Parents of the following ranks can be changed from this page: tribe, genus, subgenus, species and subspecies. Parents of children are updated in most cases, but there are edge-cases that may not be fully covered, so pay extra attention to incertae sedis taxa, and uncommon ranks such as subgenera.

Subspecies without a species is a special case that can be fixed in the normal edit form

**Comment by jonkerz** [comment]
@bpescador Perfect, I'll deploy after changing the help text.
