### ISSUE TITLE
Wiki-style help pages

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#486]
Like the GitHub wiki but hosted on AntCat and integrated into the design and editing flow.
 
Pros and cons of maintaining this code ourselves:

#### Externally hosted help pages
* Pro: The default choice is to not do this in-house.
* Con: It requires a new set of credentials or a lot of integration.
* Con: Editors will not use the GitHub or any other external wiki.

#### Internal help pages
* Pro: We already have the required functionality (markdown, history, etc, just copy-paste site notice code).
* Con: More dependency on code we may not want to get stuck with (PaperTrail, Revision Comparer). Counter argument: We don't care about history and can just copy the wiki content without history elsewhere in case we want to get rid of it.
* Pro: Linking pages internally is easier.

**Comment by jonkerz** [comment]
"add help note that includes examples format for history items" from #181

**Comment by bpescador** [comment]
Here is a link to our current external help pages on Github: https://github.com/calacademy-research/antcat/wiki

They do need more attention.

For internal help pages, I assume you are referring to tooltips?  I love tooltips -  we need more tooltips, long live tooltips.

**Comment by jonkerz** [comment]
I meant more in-depth help pages that can be edited like a wiki. The GitHub wikipages would be moved to antcat.org if we decide to do this.

Take https://github.com/calacademy-research/antcat/wiki/Adding-a-taxonomic-history-entry for example. It's already out of date and it cannot be updated except by a few editors with GitHub accounts; it's not linked from anywhere on antcat.org, and I doubt a lot of editors have even seen it :(

**Comment by bpescador** [comment]
I see your point; a wiki style help test in AntWeb would be great.
