### ISSUE TITLE
excluded from Formicidae

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#496]
Some fossil ants have been recently (and maybe wrongly) excluded from Formicidae.  For example:

†Dolichomyrma
†Khetania
The above are [incertae sedis in Aculeata]

These three 
†Archaeopone
†Armaniella
†Poneropterus

are now  [incertae sedis in Formicidae]

Note we do not want to delete the now excluded from Formicidae from AntCat because they might return to ants and we would lose their history items.

So to deal with this I propose two changed:

a) We need to change the parent of each of these genera.  Can we have the option to choose the parent as "Formicidae"  for the bottom three genera and for the top two have the Parent "Hymenoptera"  or  the superfamily rank "Formicoidea"

b) add a box check "excluded from Formicidae" and add an option to advanced search to search on all taxa excluded from Formicidae

I just remembered that there is also the Status "excluded from Formicidae" which has unclear function. If that option was selected, how does it impact the choice of the parent?

suggestions welcome

**Comment by jonkerz** [comment]
> a) We need to change the parent of each of these genera. Can we have the option to choose the parent as "Formicidae" for the bottom three genera

It sounds like this in only relevant for genera? Since species and subspecies will be transferred by implication and _incertae sedis_ in Formicidae does not make sense for ranks above genus? I can add this to the force-change parent page.

> and for the top two have the Parent "Hymenoptera" or the superfamily rank "Formicoidea"

Orders and superfamilies do not fit very well with our current hierarchy, so I think we have to live with "†_Khetania_ Dlussky, 1999 excluded for Formicidae" + a history item for the foreseeable future. We do however need a means for setting the family/subfamily/etc for these taxa to nothing.

> b) add a box check "excluded from Formicidae" and add an option to advanced search to search on all taxa excluded from Formicidae

These is an option for this in the status dropdown.

> I just remembered that there is also the Status "excluded from Formicidae" which has unclear function.

Touched briefly in #453.

> If that option was selected, how does it impact the choice of the parent?

It does not impact it at all. It's only used for the status in the header.

**Comment by bpescador** [comment]
Species and subspecies will never be incertae sedis in Formicidae.

I am fine with the solution to have the option to choose Parent for a genus as Formicidae.  I see that somehow this was already possible:  
http://antcat.org/catalog/429013
or
http://antcat.org/catalog/429012

Though it seems I can't do the same now for 
†Archaeopone
†Armaniella
†Poneropterus

And for the two fossil genera that are now excluded from Formicidae I agree that we need a blank subfamily (or maybe have the text "excluded from Formicidae"

I look forward to taking care of these minor issues - so let me know when you can push these changes live.

**Comment by jonkerz** [comment]
Deployed.

**Comment by bpescador** [comment]
@jonkerz I have been testing this tool and one issue needs corrected and help text updated.

Why it was hard to understand how to use the tool was because for most of the genera that needed updated, the "incertae sedis in was set to Family - and when that occurs, the change parent function was not present.   To get around this, I set first the incertae sedis to none and then could change the parent and then I could go back and set the incertae sedis to Family.  I think the parent change tool should be available (so you can see what the parent is set to and also change the parent if needed).

Also, the help text was not clear and before updating, I would like you to review the three cases below to make sure I understand how you propose the tool should work.  In the help text (1) below, it was not clear what was meant by "Clear parents of taxa that have been excluded from Formicidae" what do you mean by clear?  what should it be set to, Formicidae?

The current help text: 

1) Clear parents of taxa that have been excluded from Formicidae (please also update the status in the taxon form to excluded from Formicidae if that is not already the case).

2) Set a genus' parent to Formicidae if the genus is incertae sedis at family rank (please also set incertae sedis in in the taxon form to family if that is not already the case).


Three example cases that we should evaluate the fields Status, Parent and Incertae sedis.  

**Genera incertae sedis in Aculeata**  eg http://antcat.org/catalog/430181
Status: excluded from Formicidae
Parent:  ?  Formicidae
incertae sedis in ?  none?

**Genera incertae sedis in Formicidae** eg http://antcat.org/catalog/430177
Status  Valid
Parent Formicidae (not available if incertae sedis is set to Family)
Incertae sedis in Family

**Species excluded from Formicidae but parent genus still valid**: eg http://www.antcat.org/catalog/446373
Status:  excluded fro Formicidae
Parent:  valid genus name
