### ISSUE TITLE
New status - 'obsolete classification'

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#497]
@jonkerz  
A top priority is to figure out how to include subgenera in AntCat.  I am not sure of the best path forward but here is a good test case to start with:

1) http://antcat.org/catalog/507630
Camponotus (Forelophilus) Kutter, 1931 valid
Problem: this subgenus is not linked to species that should be in that subgenus
in the above case the following species should be shown:

overbecki
philippinensis
stefanschoedli

2) http://antcat.org/catalog/429306
Forelophilus Kutter, 1931 an obsolete combination of Camponotus (Forelophilus) Kutter, 1931

Like in 1 above, a genus which is changed to a subgenus becomes a dead end.  It links only to the subgenus and not to the species which were once in the genus Forelophilus

Also a subgenus name like "Camponotus (Forelophilus)" should not be part of the species name. Instead of Camponotus (Forelophilus) overbecki the name should "Camponotus overbecki"

The inclusion of subgenus rank and the possible inclusion of subtribe rank, are the last big issues that were on the to-do list for the last 5 years.   

Maybe they should be handled like Tribes.

**Comment by flaviaesteves** [comment]
### Issue

The way AntCat is currently dealing with subgenera does not conform with our code because of the available **Status** we have. For an invalid subgenus there is just two options on AntCat ([example](https://antcat.org/catalog/429247)): 
> 1. _Camponotus_ (_Colobopsis_) Mayr, 1861 **an obsolete combination** of _Colobopsis_ Mayr, 1861
However, there is no such a thing as obsolete combination for supraspecific, or uninominal, names for according to the code the term combination only describes the "association of a generic name and a specific name to form the name of a species; or of a generic name with a specific name and a subspecific name to form the name of a subspecies."

> 2. _Camponotus_ (_Colobopsis_) Mayr, 1861 **a junior synonym** of _Colobopsis_ Mayr, 1861
Another terrible choice because our code: "synonym: Each of two or more names of the **same rank** used to denote the same taxonomic taxon".

### Possible solution

The addition of a new status option (something like **obsolete classification**) would solve the problem.

**Comment by jonkerz** [comment]
@bpescador 

> 1) http://antcat.org/catalog/507630
> Camponotus (Forelophilus) Kutter, 1931 valid
> Problem: this subgenus is not linked to species that should be in that subgenus
> in the above case the following species should be shown:

Does the blue box cover this? Are we ready to make it official and show it to all visitors?

**Comment by jonkerz** [comment]
@flaviaesteves

> The addition of a new status option (something like **obsolete classification**) would solve the problem.

Sounds good. Let me ping Mark in case the AW export needs be adjusted for the new status.

Do we want to restrict `obsolete classification` to specific ranks? There is already a "research script" for https://antcat.org/database_scripts/obsolete_combinations_in_ranks_above_species

**Comment by flaviaesteves** [comment]
@jonkerz 

Yes, great idea! `obsolete classification` is restricted to supraspecific names (so is the _Status_ of each _Taxon_ listed by [obsolete combinations in ranks above species](https://antcat.org/database_scripts/obsolete_combinations_in_ranks_above_species)), and `obsolete combination` is restricted to species and subspecies names.

**Comment by bpescador** [comment]
@flaviaesteves @jonkerz

Before adding this suggested change, I would like comments on what I see as
the underlying issue. It has taken me a while to figure out how to
articulate the issue but I am hoping the following explains it. I am not
sure if the formatting will hold so I can also upload it as a pdf to the
issue chain.

Problem: When a protonym has been used at more than one rank and is also a
junior synonym, there is no "current combination, or current rank" = or the
proposed "current classification".

Background:
*Species group names: *
*between protonyms* [most common example]
invalid (unaccepted) synonyms are linked to valid (accepted): AntCat uses
*synonym* to link the two names
*within a given **protonym*
invalid (unaccepted) (as subspecies) accepted as species: use *obsolete
combination* to link the two names
only one combination, the current combination, can be linked using *synonym
*[why you ask? this rule forces protonyms to have a current combination and
listed in the current genus]
[see discussion below but I also think subspecies have a similar issue as
genus group names.]
*Genus group names differ in that there is not always a current
"combination" [or current rank]*
*Genus group names*
For an invalid (unaccepted) genus or subgenus, the valid (accepted) genus
or subgenus is the parent of the type species of the genus or subgenus.
*between protonyms* [most common example]
invalid (unaccepted) objective junior synonyms are linked to valid
(accepted): AntCat uses *synonym* to link the two names
invalid (unaccepted) objective junior synonyms are linked to valid
(accepted): AntCat uses *synonym* to link the two names
*within a given **protonym*
invalid (unaccepted) at rank genus (accepted at subgenus rank) AntCat could
use OC term to describe this
invalid (unaccepted) at rank subgenus (accepted at genus rank) AntCat could
use OC term to describe this
invalid (unaccepted) at rank subgenus (transferred as subgenus to GenusX)
AntCat could use OC to describe this
accepted at rank genus
accepted at rank subgenus
before we adopt a new term to describe the OC (Obsolete combination or
Obsolete classification, or even just unaccepted) relationships within a
given protonym, I have been thinking over the last year(s) I wanted to make
sure I we had a good model for dealing with protonyms that include OC and
synonyms. For genus group names without synonyms, I think and "OC" term
will be useful but when there is a synonym, I don't think and an "OC term"
can be used.
For species group names, we follow this rule: only one combination, the
current combination, can be linked using *synonym*
However, for genus group names, if all names are invalid, there is no
"current combination"
Thus my quandary has been: if the "accepted name" for the OCs the senior
synonym? or do we need to change how we deal with genus group names in
AntCat.
So if we follow a model where there is no current classification, then we
can look at the example below.
This is how Bolton NGC presents it:
*Taxon*
*Rank*
*Status*
*Aphaenogaster (Ischnomyrmex) <https://antcat.org/catalog/508700>*
Subgenus
unaccepted

*Ischnomyrmex <https://antcat.org/catalog/429835>*
Genus
Unaccepted (accepted as subjective junior synonym of Pheidole)
*Pheidole (Ischnomyrmex) <https://antcat.org/catalog/508704>*
Subgenus
unaccepted
*Stenamma (Ischnomyrmex) <https://antcat.org/catalog/508703>*
Subgenus
unaccepted




*Taxon*
*Rank*
*Status*
*Camponotus (Dinomyrmex) <https://antcat.org/catalog/429254>*
Subgenus
unaccepted (accepted at genus rank)
*Dinomyrmex <https://antcat.org/catalog/507605>*
Genus
accepted

So if we go with the idea there are no current "combinations" [no current
rank] then in AntCat it would be:

*Taxon*
*Rank*
*Status*
*Aphaenogaster (Ischnomyrmex) <https://antcat.org/catalog/508700>*
Subgenus
unaccepted

junior synonym of current valid taxon *Pheidole
<https://antcat.org/catalog/429833>* Westwood, 1839
*Ischnomyrmex <https://antcat.org/catalog/429835>*
Genus
unaccepted
accepted as (subjective junior synonym)
junior synonym of current valid taxon *Pheidole
<https://antcat.org/catalog/429833>* Westwood, 1839
*Pheidole (Ischnomyrmex) <https://antcat.org/catalog/508704>*
Subgenus
unaccepted

junior synonym of current valid taxon *Pheidole
<https://antcat.org/catalog/429833>* Westwood, 1839
*Stenamma (Ischnomyrmex) <https://antcat.org/catalog/508703>*
Subgenus
unaccepted
junior synonym of current valid taxon *Pheidole
<https://antcat.org/catalog/429833>* Westwood, 1839

If there are no synonyms, and one of the ranks or classification is valid
then we could use "obsolete rank" or "obsolete classification"




*Taxon*
*Rank*
*Status*
*Camponotus (Dinomyrmex) <https://antcat.org/catalog/429254>*
Subgenus
unaccepted (accepted at genus rank)
obsolete rank of Dinomyrmex
*Dinomyrmex <https://antcat.org/catalog/507605>*
Genus
accepted

As I thought about this, I realize also that for subspecies, when the name
is a junior synonym, there is also no current combination [no current rank]
for the name. How have we dealt with it? we have not, we have ignored this
point and just used the last rank the name was in before the synonymy as
the current rank. I was hoping that the solution we come up here could also
be applied in these cases too.

**Comment by bpescador** [comment]
@jonkerz @flaviaesteves 
Ok the formatting did not work when replying via email, so ignore the previous and see [here](https://www.dropbox.com/s/cvfqkfpi5wxhdlx/subgenera%20issue_v1.pdf?dl=0)

**Comment by bpescador** [comment]
@flaviaesteves @jonkerz 
Here is one possible simple solution:

For the two cases: 
**no synonyms**
When there is a valid classification within a genus-group protonym
use obsolete classification to refer to obsolete rank and obsolete genus transfers


**With synonyms [remember synonyms are applied to the protonym not a specific rank]**
invalid (unaccepted) objective/subjective junior synonyms are linked to valid (accepted): 

when a synonym is created, use the following phase as as template for all ranks of the protonym:
“Protonym a junior synonym of current valid taxon X” [the word Protonym should also be hyperlinked to the protonym in question]

eg: for Aphaenogaster (Ischnomyrmex: “Protonym a junior synonym of current valid taxon Pheidole Westwood, 1839”

by linking the protonym, this will also be more accurate.  We should also explore if this should be done at the subspecies level too.

**Comment by flaviaesteves** [comment]
@bpescador @jonkerz 

> For genus group names without synonyms, I think and "OC" term will be useful but when there is a synonym, I don't think and an "OC term" can be used. @bpescador

*I disagree to the bone!*

For genus-group names:

* If there is a synonym in the same rank, the status will be: `synonym`.
  - [*Polyrhachis* (*Anoplomyrma*)](https://antcat.org/catalog/429317) is a junior synonym of [*Polyrhachis* (*Myrma*)](https://antcat.org/catalog/429314).  

* If there is a synonym in a different rank, the status will be: `obsolete classification`.
  - [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) is **NOT** a  junior synonym of [*Colobopsis*](https://antcat.org/catalog/464151). It's a good example for this, albeit one with a complicated taxonomic history:
When the synonymy happened *Colobopsis* was being classified as [*Camponotus* (*Colobopsis*)](https://antcat.org/catalog/429247), so back in 1934 *Camponotus* (*Condylomyrma*) was a  junior synonym of of *Camponotus* (*Colobopsis*). 
But then *Camponotus* (*Colobopsis*) was raised to genus, and the change in rank also happened to *Camponotus* (*Condylomyrma*) because according to the [code](https://code.iczn.org/glossary-2/?frame=1):
    > >synonym, n. Each of two or more names of the **same rank** used to denote the same taxonomic taxon.  

    So, *Condylomyrma* is the correct `synonym` of *Colobopsis*. 
    [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) is an `obsolete classification` of *Condylomyrma*.  

>Genus group names differ in that there is not always a current "combination" [or current rank]. @bpescador

I want to clarify how the [code](https://code.iczn.org/glossary-2/?frame=1) defines rank:  

> >rank, n. The level, for nomenclatural purposes, of a taxon in a taxonomic hierarchy (e.g. all families are for nomenclatural purposes at the same rank, which lies between superfamily and subfamily). The ranks of the family group, the genus group, and the species group at which nominal taxa may be established are stated in Articles 10.3, 10.4, 35.1, 42.1 and 45.1.

So, it doesn't matter how valid or invalid is a name in the genus group, it will always have a current rank (even if the current rank is the original rank in which a name was proposed).

>For an invalid (unaccepted) genus or subgenus, the valid (accepted) genus or subgenus is the parent of the type species of the genus or subgenus. @bpescador 

I didn't understand the sentence. But just to clarify, every genus group name has a type species. If a name is invalid (a junior synonym or an un-replaced homonym), the parent of 

>When a protonym has been used at more than one rank and is also a junior synonym, there is no "current combination, or current rank" = the new "current classification"  @bpescador 

The above assertion is incorrect because "current rank" = "current classification". Rank is classification, period. And @bpescador, stop using protonym like this—protonym is just the "form" a name had when it was first published (stop using unaccepted as well, or you will end like Dubois, who only creates mess with his numerous unnecessary terms. It is no coincidence that the terms he proposed in 2000 are still not in use, but I digress).

**Comment by flaviaesteves** [comment]
In conclusion, the right thing to do *when a protonym has been used at more than one rank and is also a junior synonym* is:

1. Look at the rank the protonym had when it was proposed.
    - [*Ischnomyrmex*](https://antcat.org/protonyms/155565) was published in the genus rank. [Mayr, 1862](https://antcat.org/references/127190) stated that clearly on page 738 when he wrote *Ischnomyrmex* n. g.
2. Find out if the name is valid or invalid. If invalid go to step 3, if valid go to step 5.
    - [*Ischnomyrmex*](https://antcat.org/protonyms/155565) as junior synonym of [*Pheidole*](https://antcat.org/catalog/429833). So *Ischnomyrmex* is invalid.
3. Find out the rank of the senior synonym.
    - [*Pheidole*](https://antcat.org/catalog/429833) is a genus.
4. Are both names (junior and senior synonyms) in the same rank? If so the, the relationship between them is a synonymy. Now go to step 5.
    - Yes, both are genus.
5. Was the name used in another rank?
    - [*Ischnomyrmex*](https://antcat.org/protonyms/155565) as subgenus of [*Aphaenogaster*](https://antcat.org/catalog/429816)
    - [*Ischnomyrmex*](https://antcat.org/protonyms/155565) as subgenus of [* Stenamma*](https://antcat.org/catalog/429663)
    - [*Ischnomyrmex*](https://antcat.org/protonyms/155565) as subgenus of [*Pheidole*](https://antcat.org/catalog/429833)
6. If positive, all the other classifications of the name are `obsolete classification` of that name (i.e., `obsolete classification` of the protonym in its current rank, according to Brian's terminology). So:
    - [*Aphaenogaster* (*Ischnomyrmex*)](https://antcat.org/catalog/508700) is an `obsolete classification` of [*Ischnomyrmex*](https://antcat.org/protonyms/155565)
    - [*Stenamma* (*Ischnomyrmex*)](https://antcat.org/catalog/508703) is an `obsolete classification` of [*Ischnomyrmex*](https://antcat.org/protonyms/155565)
    - [*Pheidole* (*Ischnomyrmex*)](https://antcat.org/catalog/508704) is an `obsolete classification` of [*Ischnomyrmex*](https://antcat.org/protonyms/155565)

**Comment by flaviaesteves** [comment]
Also, I want to make it clear that the most important thing to decide the status of a name that has been used at more than one rank and is also a junior synonym is **NOT** the rank of the protonym when it was proposed. The most important factor in this decision is the current rank of the senior synonym as exemplified below.

1. Look at the rank the protonym had when it was proposed.
    - [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) was described as subgenus of [*Camponotus*](https://antcat.org/catalog/429244).
2. Find out if the name is valid or invalid. If invalid go to step 3, if valid go to step 6.
    - [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) as junior synonym of [*Colobopsis*](https://antcat.org/catalog/464151).
3. Find out the rank of the senior synonym. 
    - [*Colobopsis*](https://antcat.org/catalog/464151) is a genus
4. Are both names (junior and senior synonyms) in the same rank? If so go to step 6. If not, go to step 5.
    - No. At the moment of synonymy [*Condylomyrma*](https://antcat.org/protonyms/154978) and [*Colobopsis*](https://antcat.org/protonyms/154973) were both subgenera of [*Camponotus*](https://antcat.org/catalog/429244). But afterwards, [*Camponotus* (*Colobopsis*)](https://antcat.org/catalog/429247) was raised to genus rank, but on AntCat there is no genus name *Condylomyrma*.
5. If two or more names are considered synonyms they have to be in the same rank (following the [code](https://code.iczn.org/glossary-2/?frame=1) definition of synonym, as [quoted](https://github.com/calacademy-research/antcat/issues/497#issuecomment-646682027) before). If they are not in the same rank, the junior synonym has to be raised or demoted to the senior synonym rank. 
    - [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) has to be raised to the genus rank, as *Condylomyrma*. 
    - *Condylomyrma* (the genus) is a `synonym` of [*Colobopsis*](https://antcat.org/catalog/464151).
6. Was the name used in another rank? 
    - *Condylomyrma* (the genus, and the current combination of the protonym [Condylomyrma*](https://antcat.org/protonyms/154978)) was subgenus of [*Camponotus*](https://antcat.org/catalog/429244).
7. If positive, all the other classifications of the name are `obsolete classification` of that name in its current rank (i.e., obsolete classification of the protonym in its current rank, according to Brian's terminology; **I hope Brian now understands how problematic is his terminology**). So:
    - [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248)  is an `obsolete classification` of *Condylomyrma* (the genus).

This examples shows clearly (I hope) that if we had only looked at the protonym rank (a subgenus) we would have thought  [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) was the current classification of that name. However, following our code, the senior synonym current rank the code is what indicates that [*Camponotus* (*Condylomyrma*)](https://antcat.org/catalog/429248) is an `obsolete classification`.

**Comment by flaviaesteves** [comment]
> [remember synonyms are applied to the protonym not a specific rank] @bpescador 

I really hope you now understand that a synonymy is applied to names **in the same rank***, irrespectively of the rank of the protonym.

**Comment by bpescador** [comment]
I think the process proposed by Flavia will work and we should adopt these "rules"
for a genus group protonym:

Only one terminal rank is allowed which is either valid or a synonym with all other ranks with status "obsolete classification". 

Current rank is the rank of the valid genus group name or the rank of the senior synonym.

With synonyms linked to protonym, I would like the status for non terminal names to be changed automatically.  This would save so many headaches for editors.

One also needs to figure a better system for making sure we have all ranks in AntCat for genus group names. When we follow Bolton, we do not have to create the rank indicated:

Condylomyrma as subgenus of Camponotus: Santschi, 1928c: 72; 
Condylomyrma as junior synonym of Colobopsis: Wheeler, W.M. 1934e: 422 (in text)

Ischnomyrmex as subgenus of Stenamma: Emery, 1895a: 179 (footnote);
Ischnomyrmex as subgenus of Pheidole: Forel, 1913k: 49.
Ischnomyrmex as genus: Mayr, 1862: 738
Ischnomyrmex as junior synonym of Pheidole: Brown, 1973b: 181 

For genus-group names (note this is not true for family-group names where we need only the current classification) we need every classification.  

We could change these histories as in this example:
As subgenus of Stenamma: Stenamma (Ischnomyrmex)
or simply:
As Stenamma (Ischnomyrmex)

Thoughts? I like the second option. We would reserve "As" to indicate genus-group name classifications.  

Also, it would also make editors realize that when you add this history:
Condylomyrma as junior synonym of Colobopsis: 
You need to create Condylomyrma as a genus (which it is not currently)

I am very pleased with how this has been resolved and let me know if we should change how we indicated genus-group classification histories.

**Comment by flaviaesteves** [comment]
>We could change these histories as in this example:
As subgenus of Stenamma: Stenamma (Ischnomyrmex)
or simply:
As Stenamma (Ischnomyrmex)

The easier to implement the better, in my opinion.

**Comment by jonkerz** [comment]
TODO:

- [ ] AW export

**Comment by jonkerz** [comment]
TODO: fix "Forelophilus Kutter, 1931 an obsolete combination of Camponotus (Forelophilus) Kutter, 1931 masculine"

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/87
