### ISSUE TITLE
Automatically adding letters for year in references

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#511]
When adding references, we need to add a help menu regarding when to add a letter to the year of the references:  eg: http://antcat.org/references/127842f

see nested references, some with a letter, others without.  Shouldn't letters be added automatically when needed?

**Comment by bpescador** [comment]
I think it is fine to have the letters change when a new reference is added.  The tricky part is to develop the formula for setting the letter.  In the above example for the nested citations of Piton, 1935, the letters would be set relative to the page number.

**Comment by jonkerz** [comment]
One issue is that we store `pages_in` as strings, and we allow freeform text in this field.

What about this: Find all references with the same key. Give `a` to the first non-nested with the lowest ID. Do this for all non-nested references (`a, b, c`). Sort nested references by nesting reference, and then by the first sequence of numbers found in `pages_in`, so `Pp. 20-25` --> `20`. No number means last in the group. Use ID as a tie-breaker.

Edge cases that this formula ignores:

* `Plate 265  in:`
* `Pp. xvii-xxvii in:`
* overlapping ranges such as `20-25` / `20-24` / `21-22`

But these are edge cases so.. meh :D and believe this is not too hard to implement.

**Comment by jonkerz** [comment]
See also this link for hardcoded references with letters: http://localhost:3000/taxon_history_items?utf8=%E2%9C%93&search_type=REGEXP&q=+%5B1-9%5D%5B0-9%5D%5B0-9%5D%5B0-9%5D%5Ba-zA-z%5D

We may want to fix these before updating letters.

**Comment by bpescador** [comment]
I think your plan would work and I agree we need to remove hardcoded letters in references beforehand.  However, the link above does not return a list of references - it is for a different issue?

**Comment by jonkerz** [comment]
The link should show history items containing hardcoded references. Can you see anything?

For example this:

```
#241872 | Octella | Octella as junior synonym of Solenopsis: Taylor, 1991db: 611.
```

Where `Taylor, 1991db` is hardcoded (and it has two letters as well). Click on [`#241872`](http://antcat.org/taxon_history_items/241872) to edit the relevant history item.

**Comment by bpescador** [comment]
OK, I understand, I was thinking of hardcoded references as those who have a letter in the year field eg http://antcat.org/references/129322

**Comment by bpescador** [comment]
I started to make corrections to references that need corrected and linked here:  http://antcat.org/taxon_history_items?utf8=✓&search_type=REGEXP&q=+%5B1-9%5D%5B0-9%5D%5B0-9%5D%5B0-9%5D%5Ba-zA-z%5D

It would be great if we had someone like the person from the Wikipedia community that wanted to help fix these references.

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/23.
