### ISSUE TITLE
can't access genus header notes

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#512]
to fix these epi errors: http://antcat.org/database_scripts/epi_and_questionmark_taxt_tags
I need to access the genus header note: It does not seem available to edit.

**Comment by jonkerz** [comment]
Is it possible to use headline notes for this? Like here: http://antcat.org/catalog/429031

Because it would be neat if we could get rid of `genus_species_header_notes_taxt` altogether, since it's only being used for 6 taxa in total.

Or even just replace them with history items with the same content.

**Comment by bpescador** [comment]
Sure, that should not be a problem, though it might be good to repeat which note is which

On this page for example: http://antcat.org/taxa/429031/edit
 I see three notes fields in order:

Name note
protonym notes,
type notes

note sure which one is which
headline_notes_taxt
genus_species_header_notes_taxt

**Comment by jonkerz** [comment]
TODO

- [ ] Run script
- [ ] Remove `genus_species_header_notes_taxt` (they will all be blank by now)

```ruby
jonkerz = User.find 60
Activity.execute_script_activity jonkerz,
  "Move 'genus species header notes taxt', see %github512'"

# For PaperTrail
antcat_bot = User.find 62
PaperTrail.whodunnit = antcat_bot.id

taxa = Taxon.where.not(genus_species_header_notes_taxt: nil)

puts taxa.count
puts "ids: #{taxa.pluck :id}"

Feed.without_tracking do
  taxa.each do |taxon|
    next if taxon.headline_notes_taxt

    taxon.headline_notes_taxt = taxon.genus_species_header_notes_taxt
    taxon.genus_species_header_notes_taxt = nil
    taxon.save
  end
end; nil

puts taxa.count
```

**Comment by jonkerz** [comment]
Moved to `headline_notes_taxt`:

http://antcat.org/catalog/429535
http://antcat.org/catalog/429536
http://antcat.org/catalog/429538
http://antcat.org/catalog/429548
http://antcat.org/catalog/429555
http://antcat.org/catalog/429870
