### ISSUE TITLE
country bioregion type for replacement names

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#553]
Replacement names share the same type as the name they replace. However, currently, replacement names do not have a location and bioregion.  This is important when exporting or advance searching for names from a country or bioregion.  When a replacement name is added to the replacement field, can the location and bioregion be filled in automatically (and not changeable) from the name it is replacing?

**Comment by bpescador** [comment]
Not sure how we should handle type information when the replacement names that have their own type information such as when the replacement name is a junior synonym and hence first available replacement name. eg: 

obtusospinosa. Pheidole obtusospinosa Pergande, 1896: 889 (s.) MEXICO (Nayarit). Replacement name for Pheidole subdentata Pergande, 1896: 888. [Junior secondary homonym of Oecophthora subdentata Mayr, 1853a: 145.]

[Note: obtusospinosa junior synonym of subdentata Pergande (synonymy by Wheeler, W.M. 1914b: 50); hence obtusospinosa first available replacement name (Bolton, 1995b: 326).]
Junior synonym of subdentata Pergande: Wheeler, W.M. 1914b: 50; Creighton, 1958: 211; Gregg, R.E. 1959: 31; Smith, M.R. 1967: 355; Kempf, 1972a: 204; Smith, D.R. 1979: 1374; Brandão, 1991: 369.
Status as species: Forel, 1899c: 70; Bolton, 1995b: 326; Ward, 2000: 95 (redescription);
Mackay & Mackay, 2002: 188; Wilson, 2003: 587 (redescription).

**Comment by jonkerz** [comment]
#844 seems related.

Some investigation, more to come.

#### Where we currently have fragments of this data
* `taxa.homonym_replaced_by_id`
* In history items: ["replacement name for"](https://antcat.org/taxon_history_items?search_type=&q=replacement+name+for&taxon_type=&taxon_status=&per_page=30) on one side, and then duplicated on the other side as ["replaced by"](https://antcat.org/taxon_history_items?search_type=&q=replaced+by&taxon_type=&taxon_status=&per_page=30), ["Replacement name:"](https://antcat.org/taxon_history_items?search_type=&q=replacement+name%3A&taxon_type=&taxon_status=&per_page=30) (which in turn is duplicated in  `taxa.homonym_replaced_by_id`)

So a lot of duplication and plaintext data - it seems like all above should be a single "thing".

#### Complications
* The "junior synonym and hence first available replacement name" case you mentioned above
* [Replacement names used for more than one taxon](https://antcat.org/database_scripts/replacement_names_used_for_more_than_one_taxon)

####  Edge cases

* "unjustified subsequent designation" - https://antcat.org/taxon_history_items/240256
* "[Note: this replacement name, although proposed long ago, appears to have been mostly ignored by later authors.]" - https://antcat.org/taxon_history_items/246146
* "Unnecessary (second) replacement name for Anochetus tyrannicus Smith, 1861b: 44" - https://antcat.org/taxon_history_items/244195

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/53
