### ISSUE TITLE
Advanced search should be able to search for all changes in a given time span (year?)

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#56]
Advanced search: Search for all changes in a given year. It would be great to find all taxonomic changes in 2014 for example.

**Comment by jonkerz** [comment]
From 'change list for valid taxa', #374:

> goal: address a common request: what are the recent name changes to valid taxa over the last month or for a given date.  
>
> This could be an advanced search feature or a special script:  The list would indicate changes to valid names since a given date (the given date would have to be a recent date because AntCat may not have records of past valid taxa for more than a few years. 
>
> The first column would be the list of valid taxa on a specified date followed by author date and status (valid); the second column would be the current status of those names and any new valid taxa for the current date.

**Comment by jonkerz** [comment]
Depends on us having more normalized data (#779-ish).

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/23
