### ISSUE TITLE
Combine two genera (feature)

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#59]
[9] Genus combination (this will save a lot of data entry)

  Sink (combine) two genera

Everything gets new combinations except synonyms, which only get new parent linkage.

also creates secondary junior homonyms - check for that

also valid subspecies subspecies

[note that subsopecies aren’t “protected” by the species name - they’re at the species level for all intents and purposes]

subspecies can collide too

put in a search so we can see the collisions we create when we sink one genus into another

**Comment by jonkerz** [comment]
@bpescador Could #34 be used for this? Is it the same thing?

**Comment by bpescador** [comment]
Combine two genera is the same as create a new combination.

**Comment by jonkerz** [comment]
Gotcha, I'm closing this issue then.
