### ISSUE TITLE
Add taxa via protonym pages

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#624]
Now that we can work with protonyms, I often find myself wanting to create a taxa from a protonym page.  I was doing that with the orphaned protonyms (but now the orphaned seemed to have disappeared).  

When you edit a Protonym, would it be possible to also create a name (species, subspecies based on the protonym?

**Comment by jonkerz** [comment]
> but now the orphaned seemed to have disappeared

They were deleted as discussed in #430.

Do we want to restore them?

**Comment by bpescador** [comment]
No reason to restore them - we will rebuild them as needed when we updated
AntCat.
