### ISSUE TITLE
Documentation, elevate to species

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#64]
I noticed that when I raised Tetraponera caffra to species (using that handy “Elevate to species “ button), it was necessary to carry out two additional edits: (1) change the Name from Tetraponera natalensis caffra to Tetraponera caffra (obviously I could not do that before hitting the “Elevate…” button because Tetraponera caffra was not previously listed as a possible name); and (2) go to the old parent name, Tetraponera natalensis, and remove T. caffra as a listed subspecies.

These are reasonable steps to take, and I am not suggesting they should necessarily be automated. But if we have a “cheat sheet” for this aspect of AntCat editing (i.e., changing the rank of a name) then it would be helpful to include a description of these steps in the explanation of how to carry out the action.

**Comment by jonkerz** [comment]
Moved to the wiki: https://github.com/calacademy-research/antcat/wiki/Elevating-to-species
