### ISSUE TITLE
Show images from AntWeb

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#648]
From #174

I'm not sure how, but it would be nice.

**Comment by bpescador** [comment]
A catalog should stand on three pillars: literature, names (including history) and type specimens.  We have yet to figure out how to link each protonym (except replacement names) to their types.  We have imaged 75% of all types and they are found in Antweb.  A major milestone will be if we can find a great way to link and asses the types for every protonym.  We really don't know how many protonyms have recorded type specimens in Antweb but the goal is to eventually have them all.
