### ISSUE TITLE
Unassociated protonym names

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#68]
This query returns information about Taxa that have protonyms, and those protonyms have names that are not associated with any taxa. Except where there are minor variations in gender that you may not want to capture, I suspect many of these protonyms’ names should get primary taxon records so AntCat will be able to show all historical name variations:

mysql> SELECT pt.id taxon_id, tn.name taxon_current_name, n.name protonym_name FROM names n LEFT JOIN taxa t ON (n.id=t.name_id) LEFT JOIN protonyms p ON (n.id=p.name_id) JOIN taxa pt ON (p.id=pt.protonym_id) JOIN names tn ON (pt.name_id=tn.id) where t.id IS NULL LIMIT 500, 50;

**Comment by jonkerz** [comment]
Merged with https://github.com/calacademy-research/antcat/issues/6#issuecomment-207843982.
