### ISSUE TITLE
Possible original combinations?

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#69]
This query returns about species which are not currently in status ‘valid’ or ‘original combination’ and whose names are the same as their protonym’s name. I suspect many of these are actually original combinations and perhaps should have their status reflect that:  

mysql> SELECT t.id, t.status FROM protonyms p JOIN taxa t ON (p.name_id=t.name_id) WHERE t.status != 'original combination' AND t.status != 'valid' AND t.type='Species';

**Comment by jonkerz** [comment]
Merged with https://github.com/calacademy-research/antcat/issues/6#issuecomment-207849098.
