### ISSUE TITLE
expanded convert Bolton Key tool

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#694]
@jonkerz 
Is there any way to speed the process of adding many taxtonomic histories from Bolton to Antcat.  Instead of adding each history item one by one for a single taxon, is there a way to split one large text block into individual taxonomic history items based on the end of line or paragraph returns such as in the following. I would see it as a two step process: convert (this would allow for review) and then split into seperate entries. 

[Duplicated in Jerdon, 1854b: 105.]
[Junior primary homonym of Formica longipes Latreille, 1802c: 233 (Emery, 1921a: 25).]
Wheeler, G.C. & Wheeler, J. 1953c: 132 (l.); Imai, et al. 1984: 68 (k.).
Combination in Oecophylla: Roger, 1863b: 10;
combination in Plagiolepis: Emery, 1887a: 247;
combination in Plagiolepis (Anoplolepis): Santschi, 1914b: 123;
combination in Anoplolepis (Anoplolepis): Emery, 1925b: 17; Santschi, 1926a: 13.
Junior synonym of Oecophylla smaragdina: Smith, F. 1857a: 53; Mayr, 1872: 144; Forel, 1885b: 176.
Status as species: Smith, F. 1858b: 19; Mayr, 1863: 417; Roger, 1863b: 10; Smith, F. 1871a: 304; Emery, 1887a: 247; Emery, 1888a: 530; Emery, 1889b: 510; André, 1892b: 51; Dalla Torre, 1893: 173; Emery, 1893e: 194; Emery, 1893f: 250; Emery, 1893g: 267; Pergande, 1894: 163; Forel, 1894c: 415; Forel, 1895a: 49; Emery, 1895c: 334; Emery, 1895k: 476; Mayr, 1897: 432; Emery, 1897d: 573; Forel, 1899c: 124; Emery, 1900d: 697; Emery, 1901f: 121; Emery, 1901g: 567; Forel, 1901b: 24; Dahl, 1901: 12; Rothney, 1903: 99; Bingham, 1903: 320; Forel, 1903d: 407; Forel, 1905c: 24; Forel, 1907e: 18; Forel, 1908a: 4; Wheeler, W.M. 1908c: 166; Forel, 1909d: 229; Wheeler, W.M. 1909d: 336, 342; Forel, 1910d: 127; Yano, 1910: 421; Emery, 1911b: 532; Forel, 1911b: 207; Forel, 1912a: 72; Forel, 1912d: 109; Stitz, 1912: 510; Wheeler, W.M. 1912a: 46; Forel, 1913f: 197; Forel, 1913k: 100; Wheeler, W.M. 1913e: 237; Viehmeyer, 1914a: 114; Emery, 1914f: 420; Forel, 1915a: 34; Viehmeyer, 1916a: 145; Santschi, 1919a: 326; Wheeler, W.M. 1919e: 101; Mann, 1919: 366; Santschi, 1920h: 172; Mann, 1921: 474; Wheeler, W.M. 1922a: 933, 1036; Wheeler, W.M. 1923b: 4; Wheeler, W.M. 1924b: 253; Santschi, 1924c: 112; Emery, 1925b: 17; Stitz, 1925: 123; Mann, 1925b: 6; Mukerjee & Ribeiro, 1925: 208; Stärcke, 1926: 118 (in key); Wheeler, W.M. 1927b: 46; Wheeler, W.M. 1927d: 9; Wheeler, W.M. 1927h: 100; Santschi, 1928a: 53; Santschi, 1928c: 70; Cheesman & Crawley, 1928: 523; Wheeler, W.M. 1928c: 31; Wheeler, W.M. 1929g: 57; Karavaiev, 1930a: 213; Mukerjee, 1930: 157; Menozzi, 1930a: 3; Stärcke, 1930: 376; Wheeler, W.M. 1930h: 74; Wheeler, W.M. 1932c: 162; Menozzi, 1932d: 9; Wheeler, W.M. 1932d: 18; Wheeler, W.M. 1933a: 63; Wheeler, W.M. 1933f: 144; Wheeler, W.M. 1934a: 178; Donisthorpe, 1935: 634; Karavaiev, 1935a: 109; Goetsch & Menozzi, 1935: 99; Wheeler, W.M. 1935g: 37; Wheeler, W.M. 1936f: 15; Wheeler, W.M. 1937a: 24; Teranishi, 1940: 59; Yasumatsu, 1940a: 69; Donisthorpe, 1942d: 457; Donisthorpe, 1946e: 32; Donisthorpe, 1949b: 501; Donisthorpe, 1950a: 340; Chapman & Capco, 1951: 213; Wilson, 1962c: 18; Baltazar, 1966: 266; Wilson & Taylor, 1967: 84; Taylor, 1967b: 1094; Kempf, 1970a: 30; Kempf, 1972a: 22; Baker, 1976: 253; Snelling, R.R. & Hunt, 1976: 96; Taylor, 1976a: 87; Haines & Haines, 1978: 109; Onoyama, 1980: 199; Taylor & Brown, 1985: 108; Taylor, 1987a: 8; Rao & Veeresh, 1991: 261; Morisita, et al. 1991: 18; Dlussky, 1994: 55; Wu, J. & Wang, 1995: 132; Dorow, 1996a: 84; Tiwari, 1999: 82; Mathew & Tiwari, 2000: 348; Lin & Wu, 2003: 62.
Senior synonym of gracilipes: Emery, 1887a: 247; Dalla Torre, 1893: 173; Pergande, 1894: 163; Forel, 1894c: 415; Mayr, 1895: 149; Forel, 1899c: 124; Wheeler, W.M. 1919e: 101; Wheeler, W.M. 1922a: 933, Emery, 1925b: 17; Donisthorpe, 1932c: 444; Baltazar, 1966: 266; Kempf, 1970a: 30; Kempf, 1972a: 22.
Replacement name: Formica gracilipes Smith, F. 1857a: 55.
[Note: gracilipes Smith, F. oldest junior synonym of longipes Jerdon (synonymy by Emery, 1887a: 247, confirmed by examination of syntypic workers; hence gracilipes first available replacement name (Bolton, 1995b: 67).]

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/88
