### ISSUE TITLE
bioregion warning

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#695]
Can you create a warning on save that warns using of saving a taxon without a bioregion?  Maybe bioregion, along with the type information should be moved to the protonym page. If so, this information, along with the protonym fields should be made visible when editing a name so that the information can be checked.

**Comment by jonkerz** [comment]
Now that we have moved `biogeographic_region` to the `protonyms` table, we need to validate it in the `Protonym` model.

TODO:
- [ ] Add rank to protonym since it's only for species-group names (or use `type` of name)
- [ ] ^-- Probably after fixing unparsable names (#837)

**Comment by jonkerz** [comment]
See also #389

**Comment by jonkerz** [comment]
@bpescador Now it's soft-validated. We can add proper validations once https://antcat.org/database_scripts/species_group_protonyms_without_biogeographic_regions has been cleared.

**Comment by bpescador** [comment]
If the country is known, and the country has only one bioregion, can we
automate?  If so can you use the attached?

**Comment by jonkerz** [comment]
I will add it to the script to we can get an overview, but https://github.com/calacademy-research/antcat-issues/issues/43#issuecomment-666642519 may be an issue.

**Comment by bpescador** [comment]
agreed; we should be able to fix all those with a country.
