### ISSUE TITLE
Species with non-null epithets

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#70]
Species with a non-NULL value in the epithets field (it should be NULL):
mysql> SELECT COUNT(*) FROM names WHERE LENGTH(TRIM(name)) - LENGTH(REPLACE(TRIM(name), ' ', '')) = 1 AND epithets IS NOT NULL;

How to update these records:
mysql> UPDATE names SET epithets = NULL WHERE LENGTH(TRIM(name)) - LENGTH(REPLACE(TRIM(name), ' ', '')) = 1 AND epithets IS NOT NULL;

**Comment by jonkerz** [comment]
Merged with https://github.com/calacademy-research/antcat/issues/6#issuecomment-207843982.
