### ISSUE TITLE
Protonyms: Associate Taxonomic Histories with Protonym instead of name

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#702]
Related temporary AC wiki page: https://antcat.org/wiki_pages/7

---

@jonkerz 

Taxonomic histories should be associated with protonyms - they should be entered only once and be visible as an option for all obsolete combinations but shown for all current combinations.

Currently, taxonomic histories can be added to any combination of a protonym, leading to confusion and the need to move histories to the current name.  This should help simplify the creation of new combinations.

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/24
