### ISSUE TITLE
Bad subfamlies

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#71]
At one point there were species and subspecies which were set as having different subfamilies as their genera. This was a data corruption problem that was fixed and has not yet returned. Here is how to find and count the occurrences of this problem:

mysql> SELECT COUNT(*) FROM taxa t JOIN taxa t2 ON ((t.type='Species' OR t.type='Subspecies') AND t.genus_id=t2.id) WHERE t.subfamily_id != t2.subfamily_id OR (t.subfamily_id IS NOT NULL AND t2.subfamily_id IS NULL);

And this is how to fix the subfamilies:
mysql> UPDATE taxa t JOIN taxa t2 ON ((t.type='Species' OR t.type='Subspecies') AND t.genus_id=t2.id) SET t.subfamily_id = t2.subfamily_id WHERE t.subfamily_id != t2.subfamily_id OR (t.subfamily_id IS NOT NULL AND t2.subfamily_id IS NULL);

**Comment by jonkerz** [comment]
Merged into https://github.com/calacademy-research/antcat/issues/6#issuecomment-255056137.
