### ISSUE TITLE
Redesign how we do 'history' to use first class objects.

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#72]
This is a large task. Some notes:

[8] re-work how we do history:

History is a text field. 

Taxa should have a pointer to previous taxa. Part of creating history should be the ability to create new a new taxon record. 

Each taxon record should have a Citation.

It should be possible to edit existing taxon records to make them a part of the history for a current thing. 

We can distinguish between taxon based on protonym author and page number. This is what Flavia wants for her tell-the-difference thing.

Noted from intermediate taxa should stay in place instead of being transferred forward. When taxa are displayed, it should show those notes in the antecedent taxa.

**Comment by jonkerz** [comment]
Closing since I closed the meta issue #779. Changes will be handled one-by-one, and it will take a looong time :)
