### ISSUE TITLE
Get counts (REST API)

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#73]
We should be able to get various counts (number of species, subspecies, etc).

  Hi Brian and Stan, hope all is well over in SF. I'm wondering if either of you know of a relatively simple way to generate a list of all valid Pheidole in one column and the number of junior synonyms in another column. For example,

  Pheidole megacephala: 12
  Pheidole noda: 8
  Pheidole bilimeki: 9 >

**Comment by jonkerz** [comment]
Closing stale issue. Feel free to reopen issue if it's still relevant.
