### ISSUE TITLE
Verify coloring for unavailable misspelling

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#77]
I agree that it should be listed as purple. Joe, can you make sure all names with the category of “unavailable misspelling”  are purple and not green.

**Comment by flaviaesteves** [comment]
Please, could we discuss it before it is done? For me, those names should
only be visible as search results, as we agreed before. Please, read the my
reply to Phil's email.
Best,
Flavia

On Thursday, 1 October 2015, foozleface <notifications@github.com> wrote:

> I agree that it should be listed as purple. Joe, can you make sure all
> names with the category of “unavailable misspelling” are purple and not
> green.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy/antcat/issues/77>.
>


-- 
Flávia Esteves

Postdoctoral Fellow
Entomology
California Academy of Sciences
Golden Gate Park
55 Music Concourse Drive
San Francisco, CA 94118, U.S.A.

**Comment by jonkerz** [comment]
Closing stale issue. Feel free to reopen issue if it's still relevant.
