### ISSUE TITLE
Feature requests, uncategorized, to be split out as issues

### ISSUE THREAD

**Issue by foozleface** [calacademy-research/antcat#84]
* ~~AntBib guideline prompts: Add short guideline text to editing forms as mouse-over descriptions (e.g. tooltips) so that users do not need to refer to separate guidelines file. For example, if user hovers over ‘Author’ label, a description appears instructing user to separate author names by semicolons. If user hovers over ‘Date’ label, description text appears showing the proper date format (YYYYMMDD).~~ implemented some time ago

* ~~Catalogue editing mode: we need a tool to change the order of taxonomic history items. Something that allow the user to move an item up or down relative to other entries.~~ added in 803971b2d51636e697f83d4ddfe46ce9cf4561d5

* ~~AntBib: autogenerate pdf filename:  Have AntCat generate file name from reference metadata: Authors (et al. after 3 authors)_ year_ include title (up to 150 characters).  *\* This is to facilitate human interaction with the system.  No one sees or cares what the reference is called behind the scenes; they care only about: 1) not having to create a standard name (that represents redundant work when creating a reference), and 2) having a meaningful filename when they download a file. It cannot be a too long filename, so some parts will have to get truncated. Journal title was deemed less useful than title of the work, for that purpose.~~ split to #300

*  ~~AntBib: Remove “Cite Code” and PSW [possesses]. Those were are legacy fields of old AntBib, and have no meaning anymore.~~ split to #140 and #141

*  AntCat general: show/hide names in taxa-tree by status; i.e., add checkboxes beside the key at the bottom so the list of just valid names can be chosen, for example.

*  ~~Catalogue editing mode: create reference box for species and subspecies names (similar to the genus one)~~ #489

*  ~~Catalogue editing mode: create a button “save and add next species” -- when you are adding a bunch to new species to a given genus, so instead of going to the page you just create while adding a new species, you would be direct to the genus editing page again, saving time.~~ kinda implemented as "Taxon was successfully added. Add another *Formica* species?"

*  AntCat general: option for showing all records instead of paginated lists in the advanced search or references search

*  ~~AntCat general: have the children names of a given name visible on the regular view of AntCat (right now such list is just visible on the editing mode). That editing mode’s children names list is almost perfect, but it should also include the author(s) and description year of each child. *Keep the list in alphabetic order~~ split to #299

**Comment by jonkerz** [comment]
Closing grab-bag issue. Feel free to add new issues for anything that's still relevant and not already done.
