### ISSUE TITLE
For each Protonym: indicate when type is carried from other name

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#861]
This is important only for Homonyms and Synonyms and first available use of Quadrinomials

 Homonyms
permanent homonyms (unresolved [both have types] or with replacement" **New name takes type of old** replaced name)
conditional homonyms [both names have different types]

for synonyms
subjective synonymy, conditionally juniorised [names have different types]
objective synonyms, permanently juniorised [**names have same types**]

**Comment by jonkerz** [comment]
Probably related: #844

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/53
