### ISSUE TITLE
System for comparing names with other ant databases

### ISSUE THREAD

**Issue by jonkerz** [calacademy-research/antcat#862]

**Comment by bpescador** [comment]
@jonkerz 
The first step in creating this tool is to have a search function to create the following table for species-group names and then a second search function to create one for the genus-group names.

Species group name resolver: This table converts avatars to protonym, protonym ID, and current valid name, a similar table is needed for genus-group names

Genus | species | subspecies | AntCat ID | protonym | protonym author date page | Protonym ID | CVN Genus | CVN Species | CVN subspecies

These two tables would allow the conversion of a submitted list of species to their current valid name, would allow the conversion of any name to their protonym, would provide the antcat protonym ID (and link) for any name (a stable ID)
The genus table would provide the subfamily for any genus, the valid name for any genus.

**Comment by jonkerz** [comment]
Downloadable data from AntWiki: https://www.antwiki.org/wiki/Species_Accounts#Downloadable_Data

**Comment by jonkerz** [comment]
Moved to https://github.com/calacademy-research/antcat-issues/issues/23.
